// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_
#define FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ss {
namespace runtime {

struct PartAttributeCell;
struct PartAttributeCellBuilder;

struct Vec2;

struct U8Rect;

struct SsAttributePartColorKeyValueColor;

struct PartAttributePartColor;
struct PartAttributePartColorBuilder;

struct PartAttributeVertex;

struct PartAttributeDeform;
struct PartAttributeDeformBuilder;

struct PartAttributeShader;
struct PartAttributeShaderBuilder;

struct PartState;
struct PartStateBuilder;

struct FrameData;
struct FrameDataBuilder;

enum BlendType : uint8_t {
  BlendType_Mix = 0,
  BlendType_Mul = 1,
  BlendType_Add = 2,
  BlendType_Sub = 3,
  BlendType_Mulalpha = 4,
  BlendType_Screen = 5,
  BlendType_Exclusion = 6,
  BlendType_Invert = 7,
  BlendType_MIN = BlendType_Mix,
  BlendType_MAX = BlendType_Invert
};

inline const BlendType (&EnumValuesBlendType())[8] {
  static const BlendType values[] = {
    BlendType_Mix,
    BlendType_Mul,
    BlendType_Add,
    BlendType_Sub,
    BlendType_Mulalpha,
    BlendType_Screen,
    BlendType_Exclusion,
    BlendType_Invert
  };
  return values;
}

inline const char * const *EnumNamesBlendType() {
  static const char * const names[9] = {
    "Mix",
    "Mul",
    "Add",
    "Sub",
    "Mulalpha",
    "Screen",
    "Exclusion",
    "Invert",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlendType(BlendType e) {
  if (::flatbuffers::IsOutRange(e, BlendType_Mix, BlendType_Invert)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlendType()[index];
}

enum UpdateAttributeFlags : uint64_t {
  UpdateAttributeFlags_AttributeCell = 1ULL,
  UpdateAttributeFlags_AttributePosX = 2ULL,
  UpdateAttributeFlags_AttributePosY = 4ULL,
  UpdateAttributeFlags_AttributePosZ = 8ULL,
  UpdateAttributeFlags_AttributeRotX = 16ULL,
  UpdateAttributeFlags_AttributeRotY = 32ULL,
  UpdateAttributeFlags_AttributeRotZ = 64ULL,
  UpdateAttributeFlags_AttributeSclX = 128ULL,
  UpdateAttributeFlags_AttributeSclY = 256ULL,
  UpdateAttributeFlags_AttributeLosclX = 512ULL,
  UpdateAttributeFlags_AttributeLosclY = 1024ULL,
  UpdateAttributeFlags_AttributeAlpha = 2048ULL,
  UpdateAttributeFlags_AttributeLoAlpha = 4096ULL,
  UpdateAttributeFlags_AttributePrio = 8192ULL,
  UpdateAttributeFlags_AttributeFlipH = 16384ULL,
  UpdateAttributeFlags_AttributeFlipV = 32768ULL,
  UpdateAttributeFlags_AttributeHide = 65536ULL,
  UpdateAttributeFlags_AttributePartColor = 131072ULL,
  UpdateAttributeFlags_AttributeShader = 262144ULL,
  UpdateAttributeFlags_AttributeVertex = 524288ULL,
  UpdateAttributeFlags_AttributePivotX = 1048576ULL,
  UpdateAttributeFlags_AttributePivotY = 2097152ULL,
  UpdateAttributeFlags_AttributeAnchorX = 4194304ULL,
  UpdateAttributeFlags_AttributeAnchorY = 8388608ULL,
  UpdateAttributeFlags_AttributeSizeX = 16777216ULL,
  UpdateAttributeFlags_AttributeSizeY = 33554432ULL,
  UpdateAttributeFlags_AttributeImgFlipH = 67108864ULL,
  UpdateAttributeFlags_AttributeImgFlipV = 134217728ULL,
  UpdateAttributeFlags_AttributeUvtX = 268435456ULL,
  UpdateAttributeFlags_AttributeUvtY = 536870912ULL,
  UpdateAttributeFlags_AttributeUvrZ = 1073741824ULL,
  UpdateAttributeFlags_AttributeUvsX = 2147483648ULL,
  UpdateAttributeFlags_AttributeUvsY = 4294967296ULL,
  UpdateAttributeFlags_AttributeBoundr = 8589934592ULL,
  UpdateAttributeFlags_AttributeMask = 17179869184ULL,
  UpdateAttributeFlags_AttributeSkew = 34359738368ULL,
  UpdateAttributeFlags_AttributeDeform = 68719476736ULL,
  UpdateAttributeFlags_AttributeTexture = 137438953472ULL,
  UpdateAttributeFlags_NONE = 0,
  UpdateAttributeFlags_ANY = 274877906943ULL
};

inline const UpdateAttributeFlags (&EnumValuesUpdateAttributeFlags())[38] {
  static const UpdateAttributeFlags values[] = {
    UpdateAttributeFlags_AttributeCell,
    UpdateAttributeFlags_AttributePosX,
    UpdateAttributeFlags_AttributePosY,
    UpdateAttributeFlags_AttributePosZ,
    UpdateAttributeFlags_AttributeRotX,
    UpdateAttributeFlags_AttributeRotY,
    UpdateAttributeFlags_AttributeRotZ,
    UpdateAttributeFlags_AttributeSclX,
    UpdateAttributeFlags_AttributeSclY,
    UpdateAttributeFlags_AttributeLosclX,
    UpdateAttributeFlags_AttributeLosclY,
    UpdateAttributeFlags_AttributeAlpha,
    UpdateAttributeFlags_AttributeLoAlpha,
    UpdateAttributeFlags_AttributePrio,
    UpdateAttributeFlags_AttributeFlipH,
    UpdateAttributeFlags_AttributeFlipV,
    UpdateAttributeFlags_AttributeHide,
    UpdateAttributeFlags_AttributePartColor,
    UpdateAttributeFlags_AttributeShader,
    UpdateAttributeFlags_AttributeVertex,
    UpdateAttributeFlags_AttributePivotX,
    UpdateAttributeFlags_AttributePivotY,
    UpdateAttributeFlags_AttributeAnchorX,
    UpdateAttributeFlags_AttributeAnchorY,
    UpdateAttributeFlags_AttributeSizeX,
    UpdateAttributeFlags_AttributeSizeY,
    UpdateAttributeFlags_AttributeImgFlipH,
    UpdateAttributeFlags_AttributeImgFlipV,
    UpdateAttributeFlags_AttributeUvtX,
    UpdateAttributeFlags_AttributeUvtY,
    UpdateAttributeFlags_AttributeUvrZ,
    UpdateAttributeFlags_AttributeUvsX,
    UpdateAttributeFlags_AttributeUvsY,
    UpdateAttributeFlags_AttributeBoundr,
    UpdateAttributeFlags_AttributeMask,
    UpdateAttributeFlags_AttributeSkew,
    UpdateAttributeFlags_AttributeDeform,
    UpdateAttributeFlags_AttributeTexture
  };
  return values;
}

inline const char *EnumNameUpdateAttributeFlags(UpdateAttributeFlags e) {
  switch (e) {
    case UpdateAttributeFlags_AttributeCell: return "AttributeCell";
    case UpdateAttributeFlags_AttributePosX: return "AttributePosX";
    case UpdateAttributeFlags_AttributePosY: return "AttributePosY";
    case UpdateAttributeFlags_AttributePosZ: return "AttributePosZ";
    case UpdateAttributeFlags_AttributeRotX: return "AttributeRotX";
    case UpdateAttributeFlags_AttributeRotY: return "AttributeRotY";
    case UpdateAttributeFlags_AttributeRotZ: return "AttributeRotZ";
    case UpdateAttributeFlags_AttributeSclX: return "AttributeSclX";
    case UpdateAttributeFlags_AttributeSclY: return "AttributeSclY";
    case UpdateAttributeFlags_AttributeLosclX: return "AttributeLosclX";
    case UpdateAttributeFlags_AttributeLosclY: return "AttributeLosclY";
    case UpdateAttributeFlags_AttributeAlpha: return "AttributeAlpha";
    case UpdateAttributeFlags_AttributeLoAlpha: return "AttributeLoAlpha";
    case UpdateAttributeFlags_AttributePrio: return "AttributePrio";
    case UpdateAttributeFlags_AttributeFlipH: return "AttributeFlipH";
    case UpdateAttributeFlags_AttributeFlipV: return "AttributeFlipV";
    case UpdateAttributeFlags_AttributeHide: return "AttributeHide";
    case UpdateAttributeFlags_AttributePartColor: return "AttributePartColor";
    case UpdateAttributeFlags_AttributeShader: return "AttributeShader";
    case UpdateAttributeFlags_AttributeVertex: return "AttributeVertex";
    case UpdateAttributeFlags_AttributePivotX: return "AttributePivotX";
    case UpdateAttributeFlags_AttributePivotY: return "AttributePivotY";
    case UpdateAttributeFlags_AttributeAnchorX: return "AttributeAnchorX";
    case UpdateAttributeFlags_AttributeAnchorY: return "AttributeAnchorY";
    case UpdateAttributeFlags_AttributeSizeX: return "AttributeSizeX";
    case UpdateAttributeFlags_AttributeSizeY: return "AttributeSizeY";
    case UpdateAttributeFlags_AttributeImgFlipH: return "AttributeImgFlipH";
    case UpdateAttributeFlags_AttributeImgFlipV: return "AttributeImgFlipV";
    case UpdateAttributeFlags_AttributeUvtX: return "AttributeUvtX";
    case UpdateAttributeFlags_AttributeUvtY: return "AttributeUvtY";
    case UpdateAttributeFlags_AttributeUvrZ: return "AttributeUvrZ";
    case UpdateAttributeFlags_AttributeUvsX: return "AttributeUvsX";
    case UpdateAttributeFlags_AttributeUvsY: return "AttributeUvsY";
    case UpdateAttributeFlags_AttributeBoundr: return "AttributeBoundr";
    case UpdateAttributeFlags_AttributeMask: return "AttributeMask";
    case UpdateAttributeFlags_AttributeSkew: return "AttributeSkew";
    case UpdateAttributeFlags_AttributeDeform: return "AttributeDeform";
    case UpdateAttributeFlags_AttributeTexture: return "AttributeTexture";
    default: return "";
  }
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) U8Rect FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t a_;
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  U8Rect()
      : a_(0),
        r_(0),
        g_(0),
        b_(0) {
  }
  U8Rect(uint8_t _a, uint8_t _r, uint8_t _g, uint8_t _b)
      : a_(::flatbuffers::EndianScalar(_a)),
        r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)) {
  }
  uint8_t a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
  uint8_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(U8Rect, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) SsAttributePartColorKeyValueColor FLATBUFFERS_FINAL_CLASS {
 private:
  ss::runtime::U8Rect rgba_;
  float rate_;

 public:
  SsAttributePartColorKeyValueColor()
      : rgba_(),
        rate_(0) {
  }
  SsAttributePartColorKeyValueColor(const ss::runtime::U8Rect &_rgba, float _rate)
      : rgba_(_rgba),
        rate_(::flatbuffers::EndianScalar(_rate)) {
  }
  const ss::runtime::U8Rect &rgba() const {
    return rgba_;
  }
  float rate() const {
    return ::flatbuffers::EndianScalar(rate_);
  }
};
FLATBUFFERS_STRUCT_END(SsAttributePartColorKeyValueColor, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PartAttributeVertex FLATBUFFERS_FINAL_CLASS {
 private:
  ss::runtime::Vec2 lt_;
  ss::runtime::Vec2 rt_;
  ss::runtime::Vec2 lb_;
  ss::runtime::Vec2 rb_;

 public:
  PartAttributeVertex()
      : lt_(),
        rt_(),
        lb_(),
        rb_() {
  }
  PartAttributeVertex(const ss::runtime::Vec2 &_lt, const ss::runtime::Vec2 &_rt, const ss::runtime::Vec2 &_lb, const ss::runtime::Vec2 &_rb)
      : lt_(_lt),
        rt_(_rt),
        lb_(_lb),
        rb_(_rb) {
  }
  const ss::runtime::Vec2 &lt() const {
    return lt_;
  }
  const ss::runtime::Vec2 &rt() const {
    return rt_;
  }
  const ss::runtime::Vec2 &lb() const {
    return lb_;
  }
  const ss::runtime::Vec2 &rb() const {
    return rb_;
  }
};
FLATBUFFERS_STRUCT_END(PartAttributeVertex, 32);

struct PartAttributeCell FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeCellBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_NAME = 6
  };
  int32_t map_id() const {
    return GetField<int32_t>(VT_MAP_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct PartAttributeCellBuilder {
  typedef PartAttributeCell Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(int32_t map_id) {
    fbb_.AddElement<int32_t>(PartAttributeCell::VT_MAP_ID, map_id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PartAttributeCell::VT_NAME, name);
  }
  explicit PartAttributeCellBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeCell> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeCell>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeCell> CreatePartAttributeCell(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t map_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  PartAttributeCellBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeCell> CreatePartAttributeCellDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t map_id = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ss::runtime::CreatePartAttributeCell(
      _fbb,
      map_id,
      name__);
}

struct PartAttributePartColor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributePartColorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLEND_TYPE = 4,
    VT_LT = 6,
    VT_RT = 8,
    VT_LB = 10,
    VT_RB = 12
  };
  ss::runtime::BlendType blend_type() const {
    return static_cast<ss::runtime::BlendType>(GetField<uint8_t>(VT_BLEND_TYPE, 0));
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *lt() const {
    return GetStruct<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_LT);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *rt() const {
    return GetStruct<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_RT);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *lb() const {
    return GetStruct<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_LB);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *rb() const {
    return GetStruct<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_RB);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BLEND_TYPE, 1) &&
           VerifyField<ss::runtime::SsAttributePartColorKeyValueColor>(verifier, VT_LT, 4) &&
           VerifyField<ss::runtime::SsAttributePartColorKeyValueColor>(verifier, VT_RT, 4) &&
           VerifyField<ss::runtime::SsAttributePartColorKeyValueColor>(verifier, VT_LB, 4) &&
           VerifyField<ss::runtime::SsAttributePartColorKeyValueColor>(verifier, VT_RB, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributePartColorBuilder {
  typedef PartAttributePartColor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_blend_type(ss::runtime::BlendType blend_type) {
    fbb_.AddElement<uint8_t>(PartAttributePartColor::VT_BLEND_TYPE, static_cast<uint8_t>(blend_type), 0);
  }
  void add_lt(const ss::runtime::SsAttributePartColorKeyValueColor *lt) {
    fbb_.AddStruct(PartAttributePartColor::VT_LT, lt);
  }
  void add_rt(const ss::runtime::SsAttributePartColorKeyValueColor *rt) {
    fbb_.AddStruct(PartAttributePartColor::VT_RT, rt);
  }
  void add_lb(const ss::runtime::SsAttributePartColorKeyValueColor *lb) {
    fbb_.AddStruct(PartAttributePartColor::VT_LB, lb);
  }
  void add_rb(const ss::runtime::SsAttributePartColorKeyValueColor *rb) {
    fbb_.AddStruct(PartAttributePartColor::VT_RB, rb);
  }
  explicit PartAttributePartColorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributePartColor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributePartColor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributePartColor> CreatePartAttributePartColor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ss::runtime::BlendType blend_type = ss::runtime::BlendType_Mix,
    const ss::runtime::SsAttributePartColorKeyValueColor *lt = nullptr,
    const ss::runtime::SsAttributePartColorKeyValueColor *rt = nullptr,
    const ss::runtime::SsAttributePartColorKeyValueColor *lb = nullptr,
    const ss::runtime::SsAttributePartColorKeyValueColor *rb = nullptr) {
  PartAttributePartColorBuilder builder_(_fbb);
  builder_.add_rb(rb);
  builder_.add_lb(lb);
  builder_.add_rt(rt);
  builder_.add_lt(lt);
  builder_.add_blend_type(blend_type);
  return builder_.Finish();
}

struct PartAttributeDeform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeDeformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COORDINATE = 4,
    VT_INDEX = 6
  };
  const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *coordinate() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *>(VT_COORDINATE);
  }
  const ::flatbuffers::Vector<int16_t> *index() const {
    return GetPointer<const ::flatbuffers::Vector<int16_t> *>(VT_INDEX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COORDINATE) &&
           verifier.VerifyVector(coordinate()) &&
           VerifyOffset(verifier, VT_INDEX) &&
           verifier.VerifyVector(index()) &&
           verifier.EndTable();
  }
};

struct PartAttributeDeformBuilder {
  typedef PartAttributeDeform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_coordinate(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate) {
    fbb_.AddOffset(PartAttributeDeform::VT_COORDINATE, coordinate);
  }
  void add_index(::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index) {
    fbb_.AddOffset(PartAttributeDeform::VT_INDEX, index);
  }
  explicit PartAttributeDeformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeDeform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeDeform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index = 0) {
  PartAttributeDeformBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_coordinate(coordinate);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeformDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ss::runtime::Vec2> *coordinate = nullptr,
    const std::vector<int16_t> *index = nullptr) {
  auto coordinate__ = coordinate ? _fbb.CreateVectorOfStructs<ss::runtime::Vec2>(*coordinate) : 0;
  auto index__ = index ? _fbb.CreateVector<int16_t>(*index) : 0;
  return ss::runtime::CreatePartAttributeDeform(
      _fbb,
      coordinate__,
      index__);
}

struct PartAttributeShader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeShaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PARAM0 = 6,
    VT_PARAM1 = 8,
    VT_PARAM2 = 10,
    VT_PARAM3 = 12,
    VT_PARAM4 = 14,
    VT_PARAM5 = 16,
    VT_PARAM6 = 18,
    VT_PARAM7 = 20,
    VT_MAP0_ID = 22,
    VT_MAP0_NAME = 24,
    VT_MAP1_ID = 26,
    VT_MAP1_NAME = 28
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  float param0() const {
    return GetField<float>(VT_PARAM0, 0.0f);
  }
  float param1() const {
    return GetField<float>(VT_PARAM1, 0.0f);
  }
  float param2() const {
    return GetField<float>(VT_PARAM2, 0.0f);
  }
  float param3() const {
    return GetField<float>(VT_PARAM3, 0.0f);
  }
  float param4() const {
    return GetField<float>(VT_PARAM4, 0.0f);
  }
  float param5() const {
    return GetField<float>(VT_PARAM5, 0.0f);
  }
  float param6() const {
    return GetField<float>(VT_PARAM6, 0.0f);
  }
  float param7() const {
    return GetField<float>(VT_PARAM7, 0.0f);
  }
  int32_t map0_id() const {
    return GetField<int32_t>(VT_MAP0_ID, 0);
  }
  const ::flatbuffers::String *map0_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP0_NAME);
  }
  int32_t map1_id() const {
    return GetField<int32_t>(VT_MAP1_ID, 0);
  }
  const ::flatbuffers::String *map1_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP1_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<float>(verifier, VT_PARAM0, 4) &&
           VerifyField<float>(verifier, VT_PARAM1, 4) &&
           VerifyField<float>(verifier, VT_PARAM2, 4) &&
           VerifyField<float>(verifier, VT_PARAM3, 4) &&
           VerifyField<float>(verifier, VT_PARAM4, 4) &&
           VerifyField<float>(verifier, VT_PARAM5, 4) &&
           VerifyField<float>(verifier, VT_PARAM6, 4) &&
           VerifyField<float>(verifier, VT_PARAM7, 4) &&
           VerifyField<int32_t>(verifier, VT_MAP0_ID, 4) &&
           VerifyOffset(verifier, VT_MAP0_NAME) &&
           verifier.VerifyString(map0_name()) &&
           VerifyField<int32_t>(verifier, VT_MAP1_ID, 4) &&
           VerifyOffset(verifier, VT_MAP1_NAME) &&
           verifier.VerifyString(map1_name()) &&
           verifier.EndTable();
  }
};

struct PartAttributeShaderBuilder {
  typedef PartAttributeShader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(PartAttributeShader::VT_ID, id);
  }
  void add_param0(float param0) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM0, param0, 0.0f);
  }
  void add_param1(float param1) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM1, param1, 0.0f);
  }
  void add_param2(float param2) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM2, param2, 0.0f);
  }
  void add_param3(float param3) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM3, param3, 0.0f);
  }
  void add_param4(float param4) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM4, param4, 0.0f);
  }
  void add_param5(float param5) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM5, param5, 0.0f);
  }
  void add_param6(float param6) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM6, param6, 0.0f);
  }
  void add_param7(float param7) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM7, param7, 0.0f);
  }
  void add_map0_id(int32_t map0_id) {
    fbb_.AddElement<int32_t>(PartAttributeShader::VT_MAP0_ID, map0_id, 0);
  }
  void add_map0_name(::flatbuffers::Offset<::flatbuffers::String> map0_name) {
    fbb_.AddOffset(PartAttributeShader::VT_MAP0_NAME, map0_name);
  }
  void add_map1_id(int32_t map1_id) {
    fbb_.AddElement<int32_t>(PartAttributeShader::VT_MAP1_ID, map1_id, 0);
  }
  void add_map1_name(::flatbuffers::Offset<::flatbuffers::String> map1_name) {
    fbb_.AddOffset(PartAttributeShader::VT_MAP1_NAME, map1_name);
  }
  explicit PartAttributeShaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeShader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeShader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeShader> CreatePartAttributeShader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    float param0 = 0.0f,
    float param1 = 0.0f,
    float param2 = 0.0f,
    float param3 = 0.0f,
    float param4 = 0.0f,
    float param5 = 0.0f,
    float param6 = 0.0f,
    float param7 = 0.0f,
    int32_t map0_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map0_name = 0,
    int32_t map1_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map1_name = 0) {
  PartAttributeShaderBuilder builder_(_fbb);
  builder_.add_map1_name(map1_name);
  builder_.add_map1_id(map1_id);
  builder_.add_map0_name(map0_name);
  builder_.add_map0_id(map0_id);
  builder_.add_param7(param7);
  builder_.add_param6(param6);
  builder_.add_param5(param5);
  builder_.add_param4(param4);
  builder_.add_param3(param3);
  builder_.add_param2(param2);
  builder_.add_param1(param1);
  builder_.add_param0(param0);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeShader> CreatePartAttributeShaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    float param0 = 0.0f,
    float param1 = 0.0f,
    float param2 = 0.0f,
    float param3 = 0.0f,
    float param4 = 0.0f,
    float param5 = 0.0f,
    float param6 = 0.0f,
    float param7 = 0.0f,
    int32_t map0_id = 0,
    const char *map0_name = nullptr,
    int32_t map1_id = 0,
    const char *map1_name = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto map0_name__ = map0_name ? _fbb.CreateString(map0_name) : 0;
  auto map1_name__ = map1_name ? _fbb.CreateString(map1_name) : 0;
  return ss::runtime::CreatePartAttributeShader(
      _fbb,
      id__,
      param0,
      param1,
      param2,
      param3,
      param4,
      param5,
      param6,
      param7,
      map0_id,
      map0_name__,
      map1_id,
      map1_name__);
}

struct PartState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_UPDATE_FLAG = 6,
    VT_CELL = 8,
    VT_POSITION_X = 10,
    VT_POSITION_Y = 12,
    VT_POSITION_Z = 14,
    VT_ROTATION_X = 16,
    VT_ROTATION_Y = 18,
    VT_ROTATION_Z = 20,
    VT_SCALE_X = 22,
    VT_SCALE_Y = 24,
    VT_LOCAL_SCALE_X = 26,
    VT_LOCAL_SCALE_Y = 28,
    VT_OPACITY = 30,
    VT_LOCALOPACITY = 32,
    VT_PRIORITY = 34,
    VT_FLIP_V = 36,
    VT_FLIP_H = 38,
    VT_HIDE = 40,
    VT_PARTS_COLOR = 42,
    VT_SHADER = 44,
    VT_VERTEX = 46,
    VT_PIVOT_X = 48,
    VT_PIVOT_Y = 50,
    VT_ANCHOR_X = 52,
    VT_ANCHOR_Y = 54,
    VT_SIZE_X = 56,
    VT_SIZE_Y = 58,
    VT_IMG_FLIP_H = 60,
    VT_IMG_FLIP_V = 62,
    VT_UV_MOVE_X = 64,
    VT_UV_MOVE_Y = 66,
    VT_UV_MOVE_Z = 68,
    VT_UV_SCALE_X = 70,
    VT_UV_SCALE_Y = 72,
    VT_BOUNDING_RADIUS = 74,
    VT_MASK = 76,
    VT_SKEW_X = 78,
    VT_SKEW_Y = 80,
    VT_DEFORM = 82,
    VT_TEXTURE = 84
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  ss::runtime::UpdateAttributeFlags update_flag() const {
    return static_cast<ss::runtime::UpdateAttributeFlags>(GetField<uint64_t>(VT_UPDATE_FLAG, 0));
  }
  const ss::runtime::PartAttributeCell *cell() const {
    return GetPointer<const ss::runtime::PartAttributeCell *>(VT_CELL);
  }
  float position_x() const {
    return GetField<float>(VT_POSITION_X, 0.0f);
  }
  float position_y() const {
    return GetField<float>(VT_POSITION_Y, 0.0f);
  }
  float position_z() const {
    return GetField<float>(VT_POSITION_Z, 0.0f);
  }
  float rotation_x() const {
    return GetField<float>(VT_ROTATION_X, 0.0f);
  }
  float rotation_y() const {
    return GetField<float>(VT_ROTATION_Y, 0.0f);
  }
  float rotation_z() const {
    return GetField<float>(VT_ROTATION_Z, 0.0f);
  }
  float scale_x() const {
    return GetField<float>(VT_SCALE_X, 1.0f);
  }
  float scale_y() const {
    return GetField<float>(VT_SCALE_Y, 1.0f);
  }
  float local_scale_x() const {
    return GetField<float>(VT_LOCAL_SCALE_X, 1.0f);
  }
  float local_scale_y() const {
    return GetField<float>(VT_LOCAL_SCALE_Y, 1.0f);
  }
  float opacity() const {
    return GetField<float>(VT_OPACITY, 1.0f);
  }
  float localopacity() const {
    return GetField<float>(VT_LOCALOPACITY, 1.0f);
  }
  int32_t priority() const {
    return GetField<int32_t>(VT_PRIORITY, 0);
  }
  bool flip_v() const {
    return GetField<uint8_t>(VT_FLIP_V, 0) != 0;
  }
  bool flip_h() const {
    return GetField<uint8_t>(VT_FLIP_H, 0) != 0;
  }
  bool hide() const {
    return GetField<uint8_t>(VT_HIDE, 0) != 0;
  }
  const ss::runtime::PartAttributePartColor *parts_color() const {
    return GetPointer<const ss::runtime::PartAttributePartColor *>(VT_PARTS_COLOR);
  }
  const ss::runtime::PartAttributeShader *shader() const {
    return GetPointer<const ss::runtime::PartAttributeShader *>(VT_SHADER);
  }
  const ss::runtime::PartAttributeVertex *vertex() const {
    return GetStruct<const ss::runtime::PartAttributeVertex *>(VT_VERTEX);
  }
  float pivot_x() const {
    return GetField<float>(VT_PIVOT_X, 0.0f);
  }
  float pivot_y() const {
    return GetField<float>(VT_PIVOT_Y, 0.0f);
  }
  float anchor_x() const {
    return GetField<float>(VT_ANCHOR_X, 0.0f);
  }
  float anchor_y() const {
    return GetField<float>(VT_ANCHOR_Y, 0.0f);
  }
  float size_x() const {
    return GetField<float>(VT_SIZE_X, 1.0f);
  }
  float size_y() const {
    return GetField<float>(VT_SIZE_Y, 1.0f);
  }
  bool img_flip_h() const {
    return GetField<uint8_t>(VT_IMG_FLIP_H, 0) != 0;
  }
  bool img_flip_v() const {
    return GetField<uint8_t>(VT_IMG_FLIP_V, 0) != 0;
  }
  float uv_move_x() const {
    return GetField<float>(VT_UV_MOVE_X, 0.0f);
  }
  float uv_move_y() const {
    return GetField<float>(VT_UV_MOVE_Y, 0.0f);
  }
  float uv_move_z() const {
    return GetField<float>(VT_UV_MOVE_Z, 0.0f);
  }
  float uv_scale_x() const {
    return GetField<float>(VT_UV_SCALE_X, 1.0f);
  }
  float uv_scale_y() const {
    return GetField<float>(VT_UV_SCALE_Y, 1.0f);
  }
  float bounding_radius() const {
    return GetField<float>(VT_BOUNDING_RADIUS, 0.0f);
  }
  float mask() const {
    return GetField<float>(VT_MASK, 0.0f);
  }
  float skew_x() const {
    return GetField<float>(VT_SKEW_X, 0.0f);
  }
  float skew_y() const {
    return GetField<float>(VT_SKEW_Y, 0.0f);
  }
  const ss::runtime::PartAttributeDeform *deform() const {
    return GetPointer<const ss::runtime::PartAttributeDeform *>(VT_DEFORM);
  }
  int32_t texture() const {
    return GetField<int32_t>(VT_TEXTURE, -1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyField<uint64_t>(verifier, VT_UPDATE_FLAG, 8) &&
           VerifyOffset(verifier, VT_CELL) &&
           verifier.VerifyTable(cell()) &&
           VerifyField<float>(verifier, VT_POSITION_X, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Y, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Z, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_X, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_Y, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_Z, 4) &&
           VerifyField<float>(verifier, VT_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_LOCAL_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_LOCAL_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_OPACITY, 4) &&
           VerifyField<float>(verifier, VT_LOCALOPACITY, 4) &&
           VerifyField<int32_t>(verifier, VT_PRIORITY, 4) &&
           VerifyField<uint8_t>(verifier, VT_FLIP_V, 1) &&
           VerifyField<uint8_t>(verifier, VT_FLIP_H, 1) &&
           VerifyField<uint8_t>(verifier, VT_HIDE, 1) &&
           VerifyOffset(verifier, VT_PARTS_COLOR) &&
           verifier.VerifyTable(parts_color()) &&
           VerifyOffset(verifier, VT_SHADER) &&
           verifier.VerifyTable(shader()) &&
           VerifyField<ss::runtime::PartAttributeVertex>(verifier, VT_VERTEX, 4) &&
           VerifyField<float>(verifier, VT_PIVOT_X, 4) &&
           VerifyField<float>(verifier, VT_PIVOT_Y, 4) &&
           VerifyField<float>(verifier, VT_ANCHOR_X, 4) &&
           VerifyField<float>(verifier, VT_ANCHOR_Y, 4) &&
           VerifyField<float>(verifier, VT_SIZE_X, 4) &&
           VerifyField<float>(verifier, VT_SIZE_Y, 4) &&
           VerifyField<uint8_t>(verifier, VT_IMG_FLIP_H, 1) &&
           VerifyField<uint8_t>(verifier, VT_IMG_FLIP_V, 1) &&
           VerifyField<float>(verifier, VT_UV_MOVE_X, 4) &&
           VerifyField<float>(verifier, VT_UV_MOVE_Y, 4) &&
           VerifyField<float>(verifier, VT_UV_MOVE_Z, 4) &&
           VerifyField<float>(verifier, VT_UV_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_UV_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_BOUNDING_RADIUS, 4) &&
           VerifyField<float>(verifier, VT_MASK, 4) &&
           VerifyField<float>(verifier, VT_SKEW_X, 4) &&
           VerifyField<float>(verifier, VT_SKEW_Y, 4) &&
           VerifyOffset(verifier, VT_DEFORM) &&
           verifier.VerifyTable(deform()) &&
           VerifyField<int32_t>(verifier, VT_TEXTURE, 4) &&
           verifier.EndTable();
  }
};

struct PartStateBuilder {
  typedef PartState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(PartState::VT_PART_INDEX, part_index, 0);
  }
  void add_update_flag(ss::runtime::UpdateAttributeFlags update_flag) {
    fbb_.AddElement<uint64_t>(PartState::VT_UPDATE_FLAG, static_cast<uint64_t>(update_flag), 0);
  }
  void add_cell(::flatbuffers::Offset<ss::runtime::PartAttributeCell> cell) {
    fbb_.AddOffset(PartState::VT_CELL, cell);
  }
  void add_position_x(float position_x) {
    fbb_.AddElement<float>(PartState::VT_POSITION_X, position_x, 0.0f);
  }
  void add_position_y(float position_y) {
    fbb_.AddElement<float>(PartState::VT_POSITION_Y, position_y, 0.0f);
  }
  void add_position_z(float position_z) {
    fbb_.AddElement<float>(PartState::VT_POSITION_Z, position_z, 0.0f);
  }
  void add_rotation_x(float rotation_x) {
    fbb_.AddElement<float>(PartState::VT_ROTATION_X, rotation_x, 0.0f);
  }
  void add_rotation_y(float rotation_y) {
    fbb_.AddElement<float>(PartState::VT_ROTATION_Y, rotation_y, 0.0f);
  }
  void add_rotation_z(float rotation_z) {
    fbb_.AddElement<float>(PartState::VT_ROTATION_Z, rotation_z, 0.0f);
  }
  void add_scale_x(float scale_x) {
    fbb_.AddElement<float>(PartState::VT_SCALE_X, scale_x, 1.0f);
  }
  void add_scale_y(float scale_y) {
    fbb_.AddElement<float>(PartState::VT_SCALE_Y, scale_y, 1.0f);
  }
  void add_local_scale_x(float local_scale_x) {
    fbb_.AddElement<float>(PartState::VT_LOCAL_SCALE_X, local_scale_x, 1.0f);
  }
  void add_local_scale_y(float local_scale_y) {
    fbb_.AddElement<float>(PartState::VT_LOCAL_SCALE_Y, local_scale_y, 1.0f);
  }
  void add_opacity(float opacity) {
    fbb_.AddElement<float>(PartState::VT_OPACITY, opacity, 1.0f);
  }
  void add_localopacity(float localopacity) {
    fbb_.AddElement<float>(PartState::VT_LOCALOPACITY, localopacity, 1.0f);
  }
  void add_priority(int32_t priority) {
    fbb_.AddElement<int32_t>(PartState::VT_PRIORITY, priority, 0);
  }
  void add_flip_v(bool flip_v) {
    fbb_.AddElement<uint8_t>(PartState::VT_FLIP_V, static_cast<uint8_t>(flip_v), 0);
  }
  void add_flip_h(bool flip_h) {
    fbb_.AddElement<uint8_t>(PartState::VT_FLIP_H, static_cast<uint8_t>(flip_h), 0);
  }
  void add_hide(bool hide) {
    fbb_.AddElement<uint8_t>(PartState::VT_HIDE, static_cast<uint8_t>(hide), 0);
  }
  void add_parts_color(::flatbuffers::Offset<ss::runtime::PartAttributePartColor> parts_color) {
    fbb_.AddOffset(PartState::VT_PARTS_COLOR, parts_color);
  }
  void add_shader(::flatbuffers::Offset<ss::runtime::PartAttributeShader> shader) {
    fbb_.AddOffset(PartState::VT_SHADER, shader);
  }
  void add_vertex(const ss::runtime::PartAttributeVertex *vertex) {
    fbb_.AddStruct(PartState::VT_VERTEX, vertex);
  }
  void add_pivot_x(float pivot_x) {
    fbb_.AddElement<float>(PartState::VT_PIVOT_X, pivot_x, 0.0f);
  }
  void add_pivot_y(float pivot_y) {
    fbb_.AddElement<float>(PartState::VT_PIVOT_Y, pivot_y, 0.0f);
  }
  void add_anchor_x(float anchor_x) {
    fbb_.AddElement<float>(PartState::VT_ANCHOR_X, anchor_x, 0.0f);
  }
  void add_anchor_y(float anchor_y) {
    fbb_.AddElement<float>(PartState::VT_ANCHOR_Y, anchor_y, 0.0f);
  }
  void add_size_x(float size_x) {
    fbb_.AddElement<float>(PartState::VT_SIZE_X, size_x, 1.0f);
  }
  void add_size_y(float size_y) {
    fbb_.AddElement<float>(PartState::VT_SIZE_Y, size_y, 1.0f);
  }
  void add_img_flip_h(bool img_flip_h) {
    fbb_.AddElement<uint8_t>(PartState::VT_IMG_FLIP_H, static_cast<uint8_t>(img_flip_h), 0);
  }
  void add_img_flip_v(bool img_flip_v) {
    fbb_.AddElement<uint8_t>(PartState::VT_IMG_FLIP_V, static_cast<uint8_t>(img_flip_v), 0);
  }
  void add_uv_move_x(float uv_move_x) {
    fbb_.AddElement<float>(PartState::VT_UV_MOVE_X, uv_move_x, 0.0f);
  }
  void add_uv_move_y(float uv_move_y) {
    fbb_.AddElement<float>(PartState::VT_UV_MOVE_Y, uv_move_y, 0.0f);
  }
  void add_uv_move_z(float uv_move_z) {
    fbb_.AddElement<float>(PartState::VT_UV_MOVE_Z, uv_move_z, 0.0f);
  }
  void add_uv_scale_x(float uv_scale_x) {
    fbb_.AddElement<float>(PartState::VT_UV_SCALE_X, uv_scale_x, 1.0f);
  }
  void add_uv_scale_y(float uv_scale_y) {
    fbb_.AddElement<float>(PartState::VT_UV_SCALE_Y, uv_scale_y, 1.0f);
  }
  void add_bounding_radius(float bounding_radius) {
    fbb_.AddElement<float>(PartState::VT_BOUNDING_RADIUS, bounding_radius, 0.0f);
  }
  void add_mask(float mask) {
    fbb_.AddElement<float>(PartState::VT_MASK, mask, 0.0f);
  }
  void add_skew_x(float skew_x) {
    fbb_.AddElement<float>(PartState::VT_SKEW_X, skew_x, 0.0f);
  }
  void add_skew_y(float skew_y) {
    fbb_.AddElement<float>(PartState::VT_SKEW_Y, skew_y, 0.0f);
  }
  void add_deform(::flatbuffers::Offset<ss::runtime::PartAttributeDeform> deform) {
    fbb_.AddOffset(PartState::VT_DEFORM, deform);
  }
  void add_texture(int32_t texture) {
    fbb_.AddElement<int32_t>(PartState::VT_TEXTURE, texture, -1);
  }
  explicit PartStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartState> CreatePartState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ss::runtime::UpdateAttributeFlags update_flag = static_cast<ss::runtime::UpdateAttributeFlags>(0),
    ::flatbuffers::Offset<ss::runtime::PartAttributeCell> cell = 0,
    float position_x = 0.0f,
    float position_y = 0.0f,
    float position_z = 0.0f,
    float rotation_x = 0.0f,
    float rotation_y = 0.0f,
    float rotation_z = 0.0f,
    float scale_x = 1.0f,
    float scale_y = 1.0f,
    float local_scale_x = 1.0f,
    float local_scale_y = 1.0f,
    float opacity = 1.0f,
    float localopacity = 1.0f,
    int32_t priority = 0,
    bool flip_v = false,
    bool flip_h = false,
    bool hide = false,
    ::flatbuffers::Offset<ss::runtime::PartAttributePartColor> parts_color = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeShader> shader = 0,
    const ss::runtime::PartAttributeVertex *vertex = nullptr,
    float pivot_x = 0.0f,
    float pivot_y = 0.0f,
    float anchor_x = 0.0f,
    float anchor_y = 0.0f,
    float size_x = 1.0f,
    float size_y = 1.0f,
    bool img_flip_h = false,
    bool img_flip_v = false,
    float uv_move_x = 0.0f,
    float uv_move_y = 0.0f,
    float uv_move_z = 0.0f,
    float uv_scale_x = 1.0f,
    float uv_scale_y = 1.0f,
    float bounding_radius = 0.0f,
    float mask = 0.0f,
    float skew_x = 0.0f,
    float skew_y = 0.0f,
    ::flatbuffers::Offset<ss::runtime::PartAttributeDeform> deform = 0,
    int32_t texture = -1) {
  PartStateBuilder builder_(_fbb);
  builder_.add_update_flag(update_flag);
  builder_.add_texture(texture);
  builder_.add_deform(deform);
  builder_.add_skew_y(skew_y);
  builder_.add_skew_x(skew_x);
  builder_.add_mask(mask);
  builder_.add_bounding_radius(bounding_radius);
  builder_.add_uv_scale_y(uv_scale_y);
  builder_.add_uv_scale_x(uv_scale_x);
  builder_.add_uv_move_z(uv_move_z);
  builder_.add_uv_move_y(uv_move_y);
  builder_.add_uv_move_x(uv_move_x);
  builder_.add_size_y(size_y);
  builder_.add_size_x(size_x);
  builder_.add_anchor_y(anchor_y);
  builder_.add_anchor_x(anchor_x);
  builder_.add_pivot_y(pivot_y);
  builder_.add_pivot_x(pivot_x);
  builder_.add_vertex(vertex);
  builder_.add_shader(shader);
  builder_.add_parts_color(parts_color);
  builder_.add_priority(priority);
  builder_.add_localopacity(localopacity);
  builder_.add_opacity(opacity);
  builder_.add_local_scale_y(local_scale_y);
  builder_.add_local_scale_x(local_scale_x);
  builder_.add_scale_y(scale_y);
  builder_.add_scale_x(scale_x);
  builder_.add_rotation_z(rotation_z);
  builder_.add_rotation_y(rotation_y);
  builder_.add_rotation_x(rotation_x);
  builder_.add_position_z(position_z);
  builder_.add_position_y(position_y);
  builder_.add_position_x(position_x);
  builder_.add_cell(cell);
  builder_.add_part_index(part_index);
  builder_.add_img_flip_v(img_flip_v);
  builder_.add_img_flip_h(img_flip_h);
  builder_.add_hide(hide);
  builder_.add_flip_h(flip_h);
  builder_.add_flip_v(flip_v);
  return builder_.Finish();
}

struct FrameData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FrameDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartState>> *parts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartState>> *>(VT_PARTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARTS) &&
           verifier.VerifyVector(parts()) &&
           verifier.VerifyVectorOfTables(parts()) &&
           verifier.EndTable();
  }
};

struct FrameDataBuilder {
  typedef FrameData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartState>>> parts) {
    fbb_.AddOffset(FrameData::VT_PARTS, parts);
  }
  explicit FrameDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FrameData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FrameData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FrameData> CreateFrameData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartState>>> parts = 0) {
  FrameDataBuilder builder_(_fbb);
  builder_.add_parts(parts);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FrameData> CreateFrameDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ss::runtime::PartState>> *parts = nullptr) {
  auto parts__ = parts ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::PartState>>(*parts) : 0;
  return ss::runtime::CreateFrameData(
      _fbb,
      parts__);
}

inline const ss::runtime::FrameData *GetFrameData(const void *buf) {
  return ::flatbuffers::GetRoot<ss::runtime::FrameData>(buf);
}

inline const ss::runtime::FrameData *GetSizePrefixedFrameData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ss::runtime::FrameData>(buf);
}

template <bool B = false>
inline bool VerifyFrameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ss::runtime::FrameData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedFrameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ss::runtime::FrameData>(nullptr);
}

inline void FinishFrameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::FrameData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFrameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::FrameData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace runtime
}  // namespace ss

#endif  // FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_
