// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PREPARATION_SS_RUNTIME_H_
#define FLATBUFFERS_GENERATED_PREPARATION_SS_RUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ss {
namespace runtime {

struct Vec2;

struct U8Rect;

struct Rect;

struct IntValueEntry;
struct IntValueEntryBuilder;

struct PartAttributeCell;
struct PartAttributeCellBuilder;

struct SsAttributePartColorKeyValueColor;
struct SsAttributePartColorKeyValueColorBuilder;

struct PartAttributePartColor;
struct PartAttributePartColorBuilder;

struct PartAttributeVertex;
struct PartAttributeVertexBuilder;

struct PartAttributeInstance;
struct PartAttributeInstanceBuilder;

struct PartAttributeEffect;
struct PartAttributeEffectBuilder;

struct PartAttributeDeform;
struct PartAttributeDeformBuilder;

struct PartAttributeShader;
struct PartAttributeShaderBuilder;

struct PartAttributeUserData;
struct PartAttributeUserDataBuilder;

struct SignalCommandParam;
struct SignalCommandParamBuilder;

struct PartAttributeSignal;
struct PartAttributeSignalBuilder;

struct PartAttributeAudio;
struct PartAttributeAudioBuilder;

struct PartAttributes;
struct PartAttributesBuilder;

struct PartMeshData;
struct PartMeshDataBuilder;

struct EventUserData;
struct EventUserDataBuilder;

struct EventSignal;
struct EventSignalBuilder;

struct EventAudio;
struct EventAudioBuilder;

struct EventInstance;
struct EventInstanceBuilder;

struct EventEffect;
struct EventEffectBuilder;

struct EventsPerFrame;
struct EventsPerFrameBuilder;

struct Label;
struct LabelBuilder;

struct AnimPrepData;
struct AnimPrepDataBuilder;

enum BlendType : uint8_t {
  BlendType_Mix = 0,
  BlendType_Mul = 1,
  BlendType_Add = 2,
  BlendType_Sub = 3,
  BlendType_Mulalpha = 4,
  BlendType_Screen = 5,
  BlendType_Exclusion = 6,
  BlendType_Invert = 7,
  BlendType_MIN = BlendType_Mix,
  BlendType_MAX = BlendType_Invert
};

inline const BlendType (&EnumValuesBlendType())[8] {
  static const BlendType values[] = {
    BlendType_Mix,
    BlendType_Mul,
    BlendType_Add,
    BlendType_Sub,
    BlendType_Mulalpha,
    BlendType_Screen,
    BlendType_Exclusion,
    BlendType_Invert
  };
  return values;
}

inline const char * const *EnumNamesBlendType() {
  static const char * const names[9] = {
    "Mix",
    "Mul",
    "Add",
    "Sub",
    "Mulalpha",
    "Screen",
    "Exclusion",
    "Invert",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlendType(BlendType e) {
  if (::flatbuffers::IsOutRange(e, BlendType_Mix, BlendType_Invert)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlendType()[index];
}

enum SignalCommandParamType : uint8_t {
  SignalCommandParamType_Index = 0,
  SignalCommandParamType_Integer = 1,
  SignalCommandParamType_Floating = 2,
  SignalCommandParamType_None = 3,
  SignalCommandParamType_MIN = SignalCommandParamType_Index,
  SignalCommandParamType_MAX = SignalCommandParamType_None
};

inline const SignalCommandParamType (&EnumValuesSignalCommandParamType())[4] {
  static const SignalCommandParamType values[] = {
    SignalCommandParamType_Index,
    SignalCommandParamType_Integer,
    SignalCommandParamType_Floating,
    SignalCommandParamType_None
  };
  return values;
}

inline const char * const *EnumNamesSignalCommandParamType() {
  static const char * const names[5] = {
    "Index",
    "Integer",
    "Floating",
    "None",
    nullptr
  };
  return names;
}

inline const char *EnumNameSignalCommandParamType(SignalCommandParamType e) {
  if (::flatbuffers::IsOutRange(e, SignalCommandParamType_Index, SignalCommandParamType_None)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSignalCommandParamType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) U8Rect FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t a_;
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  U8Rect()
      : a_(0),
        r_(0),
        g_(0),
        b_(0) {
  }
  U8Rect(uint8_t _a, uint8_t _r, uint8_t _g, uint8_t _b)
      : a_(::flatbuffers::EndianScalar(_a)),
        r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)) {
  }
  uint8_t a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
  uint8_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(U8Rect, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Rect FLATBUFFERS_FINAL_CLASS {
 private:
  float x1_;
  float y1_;
  float x2_;
  float y2_;

 public:
  Rect()
      : x1_(0),
        y1_(0),
        x2_(0),
        y2_(0) {
  }
  Rect(float _x1, float _y1, float _x2, float _y2)
      : x1_(::flatbuffers::EndianScalar(_x1)),
        y1_(::flatbuffers::EndianScalar(_y1)),
        x2_(::flatbuffers::EndianScalar(_x2)),
        y2_(::flatbuffers::EndianScalar(_y2)) {
  }
  float x1() const {
    return ::flatbuffers::EndianScalar(x1_);
  }
  float y1() const {
    return ::flatbuffers::EndianScalar(y1_);
  }
  float x2() const {
    return ::flatbuffers::EndianScalar(x2_);
  }
  float y2() const {
    return ::flatbuffers::EndianScalar(y2_);
  }
};
FLATBUFFERS_STRUCT_END(Rect, 16);

struct IntValueEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntValueEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct IntValueEntryBuilder {
  typedef IntValueEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(IntValueEntry::VT_VALUE, value, 0);
  }
  explicit IntValueEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IntValueEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IntValueEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IntValueEntry> CreateIntValueEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t value = 0) {
  IntValueEntryBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct PartAttributeCell FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeCellBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAP_ID = 4,
    VT_NAME = 6
  };
  int32_t map_id() const {
    return GetField<int32_t>(VT_MAP_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MAP_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct PartAttributeCellBuilder {
  typedef PartAttributeCell Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_map_id(int32_t map_id) {
    fbb_.AddElement<int32_t>(PartAttributeCell::VT_MAP_ID, map_id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PartAttributeCell::VT_NAME, name);
  }
  explicit PartAttributeCellBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeCell> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeCell>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeCell> CreatePartAttributeCell(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t map_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  PartAttributeCellBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_map_id(map_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeCell> CreatePartAttributeCellDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t map_id = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ss::runtime::CreatePartAttributeCell(
      _fbb,
      map_id,
      name__);
}

struct SsAttributePartColorKeyValueColor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SsAttributePartColorKeyValueColorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RGBA = 4,
    VT_RATE = 6
  };
  const ss::runtime::U8Rect *rgba() const {
    return GetStruct<const ss::runtime::U8Rect *>(VT_RGBA);
  }
  float rate() const {
    return GetField<float>(VT_RATE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ss::runtime::U8Rect>(verifier, VT_RGBA, 1) &&
           VerifyField<float>(verifier, VT_RATE, 4) &&
           verifier.EndTable();
  }
};

struct SsAttributePartColorKeyValueColorBuilder {
  typedef SsAttributePartColorKeyValueColor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rgba(const ss::runtime::U8Rect *rgba) {
    fbb_.AddStruct(SsAttributePartColorKeyValueColor::VT_RGBA, rgba);
  }
  void add_rate(float rate) {
    fbb_.AddElement<float>(SsAttributePartColorKeyValueColor::VT_RATE, rate, 0.0f);
  }
  explicit SsAttributePartColorKeyValueColorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SsAttributePartColorKeyValueColor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SsAttributePartColorKeyValueColor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SsAttributePartColorKeyValueColor> CreateSsAttributePartColorKeyValueColor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ss::runtime::U8Rect *rgba = nullptr,
    float rate = 0.0f) {
  SsAttributePartColorKeyValueColorBuilder builder_(_fbb);
  builder_.add_rate(rate);
  builder_.add_rgba(rgba);
  return builder_.Finish();
}

struct PartAttributePartColor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributePartColorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLEND_TYPE = 4,
    VT_LT = 6,
    VT_RT = 8,
    VT_LB = 10,
    VT_RB = 12
  };
  ss::runtime::BlendType blend_type() const {
    return static_cast<ss::runtime::BlendType>(GetField<uint8_t>(VT_BLEND_TYPE, 0));
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *lt() const {
    return GetPointer<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_LT);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *rt() const {
    return GetPointer<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_RT);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *lb() const {
    return GetPointer<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_LB);
  }
  const ss::runtime::SsAttributePartColorKeyValueColor *rb() const {
    return GetPointer<const ss::runtime::SsAttributePartColorKeyValueColor *>(VT_RB);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BLEND_TYPE, 1) &&
           VerifyOffset(verifier, VT_LT) &&
           verifier.VerifyTable(lt()) &&
           VerifyOffset(verifier, VT_RT) &&
           verifier.VerifyTable(rt()) &&
           VerifyOffset(verifier, VT_LB) &&
           verifier.VerifyTable(lb()) &&
           VerifyOffset(verifier, VT_RB) &&
           verifier.VerifyTable(rb()) &&
           verifier.EndTable();
  }
};

struct PartAttributePartColorBuilder {
  typedef PartAttributePartColor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_blend_type(ss::runtime::BlendType blend_type) {
    fbb_.AddElement<uint8_t>(PartAttributePartColor::VT_BLEND_TYPE, static_cast<uint8_t>(blend_type), 0);
  }
  void add_lt(::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> lt) {
    fbb_.AddOffset(PartAttributePartColor::VT_LT, lt);
  }
  void add_rt(::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> rt) {
    fbb_.AddOffset(PartAttributePartColor::VT_RT, rt);
  }
  void add_lb(::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> lb) {
    fbb_.AddOffset(PartAttributePartColor::VT_LB, lb);
  }
  void add_rb(::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> rb) {
    fbb_.AddOffset(PartAttributePartColor::VT_RB, rb);
  }
  explicit PartAttributePartColorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributePartColor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributePartColor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributePartColor> CreatePartAttributePartColor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ss::runtime::BlendType blend_type = ss::runtime::BlendType_Mix,
    ::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> lt = 0,
    ::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> rt = 0,
    ::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> lb = 0,
    ::flatbuffers::Offset<ss::runtime::SsAttributePartColorKeyValueColor> rb = 0) {
  PartAttributePartColorBuilder builder_(_fbb);
  builder_.add_rb(rb);
  builder_.add_lb(lb);
  builder_.add_rt(rt);
  builder_.add_lt(lt);
  builder_.add_blend_type(blend_type);
  return builder_.Finish();
}

struct PartAttributeVertex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeVertexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LT = 4,
    VT_RT = 6,
    VT_LB = 8,
    VT_RB = 10
  };
  const ss::runtime::Vec2 *lt() const {
    return GetStruct<const ss::runtime::Vec2 *>(VT_LT);
  }
  const ss::runtime::Vec2 *rt() const {
    return GetStruct<const ss::runtime::Vec2 *>(VT_RT);
  }
  const ss::runtime::Vec2 *lb() const {
    return GetStruct<const ss::runtime::Vec2 *>(VT_LB);
  }
  const ss::runtime::Vec2 *rb() const {
    return GetStruct<const ss::runtime::Vec2 *>(VT_RB);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ss::runtime::Vec2>(verifier, VT_LT, 4) &&
           VerifyField<ss::runtime::Vec2>(verifier, VT_RT, 4) &&
           VerifyField<ss::runtime::Vec2>(verifier, VT_LB, 4) &&
           VerifyField<ss::runtime::Vec2>(verifier, VT_RB, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributeVertexBuilder {
  typedef PartAttributeVertex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_lt(const ss::runtime::Vec2 *lt) {
    fbb_.AddStruct(PartAttributeVertex::VT_LT, lt);
  }
  void add_rt(const ss::runtime::Vec2 *rt) {
    fbb_.AddStruct(PartAttributeVertex::VT_RT, rt);
  }
  void add_lb(const ss::runtime::Vec2 *lb) {
    fbb_.AddStruct(PartAttributeVertex::VT_LB, lb);
  }
  void add_rb(const ss::runtime::Vec2 *rb) {
    fbb_.AddStruct(PartAttributeVertex::VT_RB, rb);
  }
  explicit PartAttributeVertexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeVertex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeVertex>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeVertex> CreatePartAttributeVertex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ss::runtime::Vec2 *lt = nullptr,
    const ss::runtime::Vec2 *rt = nullptr,
    const ss::runtime::Vec2 *lb = nullptr,
    const ss::runtime::Vec2 *rb = nullptr) {
  PartAttributeVertexBuilder builder_(_fbb);
  builder_.add_rb(rb);
  builder_.add_lb(lb);
  builder_.add_rt(rt);
  builder_.add_lt(lt);
  return builder_.Finish();
}

struct PartAttributeInstance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeInstanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PINGPONG = 4,
    VT_INDEPENDENT = 6,
    VT_LOOP_NUM = 8,
    VT_START_LABEL = 10,
    VT_START_OFFSET = 12,
    VT_END_LABEL = 14,
    VT_END_OFFSET = 16,
    VT_SPEED = 18
  };
  bool pingpong() const {
    return GetField<uint8_t>(VT_PINGPONG, 0) != 0;
  }
  bool independent() const {
    return GetField<uint8_t>(VT_INDEPENDENT, 0) != 0;
  }
  int32_t loop_num() const {
    return GetField<int32_t>(VT_LOOP_NUM, 0);
  }
  const ::flatbuffers::String *start_label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_START_LABEL);
  }
  int32_t start_offset() const {
    return GetField<int32_t>(VT_START_OFFSET, 0);
  }
  const ::flatbuffers::String *end_label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_END_LABEL);
  }
  int32_t end_offset() const {
    return GetField<int32_t>(VT_END_OFFSET, 0);
  }
  float speed() const {
    return GetField<float>(VT_SPEED, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PINGPONG, 1) &&
           VerifyField<uint8_t>(verifier, VT_INDEPENDENT, 1) &&
           VerifyField<int32_t>(verifier, VT_LOOP_NUM, 4) &&
           VerifyOffset(verifier, VT_START_LABEL) &&
           verifier.VerifyString(start_label()) &&
           VerifyField<int32_t>(verifier, VT_START_OFFSET, 4) &&
           VerifyOffset(verifier, VT_END_LABEL) &&
           verifier.VerifyString(end_label()) &&
           VerifyField<int32_t>(verifier, VT_END_OFFSET, 4) &&
           VerifyField<float>(verifier, VT_SPEED, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributeInstanceBuilder {
  typedef PartAttributeInstance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pingpong(bool pingpong) {
    fbb_.AddElement<uint8_t>(PartAttributeInstance::VT_PINGPONG, static_cast<uint8_t>(pingpong), 0);
  }
  void add_independent(bool independent) {
    fbb_.AddElement<uint8_t>(PartAttributeInstance::VT_INDEPENDENT, static_cast<uint8_t>(independent), 0);
  }
  void add_loop_num(int32_t loop_num) {
    fbb_.AddElement<int32_t>(PartAttributeInstance::VT_LOOP_NUM, loop_num, 0);
  }
  void add_start_label(::flatbuffers::Offset<::flatbuffers::String> start_label) {
    fbb_.AddOffset(PartAttributeInstance::VT_START_LABEL, start_label);
  }
  void add_start_offset(int32_t start_offset) {
    fbb_.AddElement<int32_t>(PartAttributeInstance::VT_START_OFFSET, start_offset, 0);
  }
  void add_end_label(::flatbuffers::Offset<::flatbuffers::String> end_label) {
    fbb_.AddOffset(PartAttributeInstance::VT_END_LABEL, end_label);
  }
  void add_end_offset(int32_t end_offset) {
    fbb_.AddElement<int32_t>(PartAttributeInstance::VT_END_OFFSET, end_offset, 0);
  }
  void add_speed(float speed) {
    fbb_.AddElement<float>(PartAttributeInstance::VT_SPEED, speed, 0.0f);
  }
  explicit PartAttributeInstanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeInstance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeInstance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeInstance> CreatePartAttributeInstance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool pingpong = false,
    bool independent = false,
    int32_t loop_num = 0,
    ::flatbuffers::Offset<::flatbuffers::String> start_label = 0,
    int32_t start_offset = 0,
    ::flatbuffers::Offset<::flatbuffers::String> end_label = 0,
    int32_t end_offset = 0,
    float speed = 0.0f) {
  PartAttributeInstanceBuilder builder_(_fbb);
  builder_.add_speed(speed);
  builder_.add_end_offset(end_offset);
  builder_.add_end_label(end_label);
  builder_.add_start_offset(start_offset);
  builder_.add_start_label(start_label);
  builder_.add_loop_num(loop_num);
  builder_.add_independent(independent);
  builder_.add_pingpong(pingpong);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeInstance> CreatePartAttributeInstanceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool pingpong = false,
    bool independent = false,
    int32_t loop_num = 0,
    const char *start_label = nullptr,
    int32_t start_offset = 0,
    const char *end_label = nullptr,
    int32_t end_offset = 0,
    float speed = 0.0f) {
  auto start_label__ = start_label ? _fbb.CreateString(start_label) : 0;
  auto end_label__ = end_label ? _fbb.CreateString(end_label) : 0;
  return ss::runtime::CreatePartAttributeInstance(
      _fbb,
      pingpong,
      independent,
      loop_num,
      start_label__,
      start_offset,
      end_label__,
      end_offset,
      speed);
}

struct PartAttributeEffect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeEffectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CUR_KEYFRAME = 4,
    VT_START_TIME = 6,
    VT_SPEED = 8,
    VT_LOOPFLAG = 10
  };
  int32_t cur_keyframe() const {
    return GetField<int32_t>(VT_CUR_KEYFRAME, 0);
  }
  int32_t start_time() const {
    return GetField<int32_t>(VT_START_TIME, 0);
  }
  float speed() const {
    return GetField<float>(VT_SPEED, 0.0f);
  }
  int32_t loopflag() const {
    return GetField<int32_t>(VT_LOOPFLAG, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CUR_KEYFRAME, 4) &&
           VerifyField<int32_t>(verifier, VT_START_TIME, 4) &&
           VerifyField<float>(verifier, VT_SPEED, 4) &&
           VerifyField<int32_t>(verifier, VT_LOOPFLAG, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributeEffectBuilder {
  typedef PartAttributeEffect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cur_keyframe(int32_t cur_keyframe) {
    fbb_.AddElement<int32_t>(PartAttributeEffect::VT_CUR_KEYFRAME, cur_keyframe, 0);
  }
  void add_start_time(int32_t start_time) {
    fbb_.AddElement<int32_t>(PartAttributeEffect::VT_START_TIME, start_time, 0);
  }
  void add_speed(float speed) {
    fbb_.AddElement<float>(PartAttributeEffect::VT_SPEED, speed, 0.0f);
  }
  void add_loopflag(int32_t loopflag) {
    fbb_.AddElement<int32_t>(PartAttributeEffect::VT_LOOPFLAG, loopflag, 0);
  }
  explicit PartAttributeEffectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeEffect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeEffect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeEffect> CreatePartAttributeEffect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t cur_keyframe = 0,
    int32_t start_time = 0,
    float speed = 0.0f,
    int32_t loopflag = 0) {
  PartAttributeEffectBuilder builder_(_fbb);
  builder_.add_loopflag(loopflag);
  builder_.add_speed(speed);
  builder_.add_start_time(start_time);
  builder_.add_cur_keyframe(cur_keyframe);
  return builder_.Finish();
}

struct PartAttributeDeform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeDeformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COORDINATE = 4,
    VT_INDEX = 6
  };
  const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *coordinate() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *>(VT_COORDINATE);
  }
  const ::flatbuffers::Vector<int16_t> *index() const {
    return GetPointer<const ::flatbuffers::Vector<int16_t> *>(VT_INDEX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COORDINATE) &&
           verifier.VerifyVector(coordinate()) &&
           VerifyOffset(verifier, VT_INDEX) &&
           verifier.VerifyVector(index()) &&
           verifier.EndTable();
  }
};

struct PartAttributeDeformBuilder {
  typedef PartAttributeDeform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_coordinate(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate) {
    fbb_.AddOffset(PartAttributeDeform::VT_COORDINATE, coordinate);
  }
  void add_index(::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index) {
    fbb_.AddOffset(PartAttributeDeform::VT_INDEX, index);
  }
  explicit PartAttributeDeformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeDeform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeDeform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index = 0) {
  PartAttributeDeformBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_coordinate(coordinate);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeformDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ss::runtime::Vec2> *coordinate = nullptr,
    const std::vector<int16_t> *index = nullptr) {
  auto coordinate__ = coordinate ? _fbb.CreateVectorOfStructs<ss::runtime::Vec2>(*coordinate) : 0;
  auto index__ = index ? _fbb.CreateVector<int16_t>(*index) : 0;
  return ss::runtime::CreatePartAttributeDeform(
      _fbb,
      coordinate__,
      index__);
}

struct PartAttributeShader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeShaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PARAM0 = 6,
    VT_PARAM1 = 8,
    VT_PARAM2 = 10,
    VT_PARAM3 = 12,
    VT_PARAM4 = 14,
    VT_PARAM5 = 16,
    VT_PARAM6 = 18,
    VT_PARAM7 = 20,
    VT_MAP0_ID = 22,
    VT_MAP0_NAME = 24,
    VT_MAP1_ID = 26,
    VT_MAP1_NAME = 28
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  float param0() const {
    return GetField<float>(VT_PARAM0, 0.0f);
  }
  float param1() const {
    return GetField<float>(VT_PARAM1, 0.0f);
  }
  float param2() const {
    return GetField<float>(VT_PARAM2, 0.0f);
  }
  float param3() const {
    return GetField<float>(VT_PARAM3, 0.0f);
  }
  float param4() const {
    return GetField<float>(VT_PARAM4, 0.0f);
  }
  float param5() const {
    return GetField<float>(VT_PARAM5, 0.0f);
  }
  float param6() const {
    return GetField<float>(VT_PARAM6, 0.0f);
  }
  float param7() const {
    return GetField<float>(VT_PARAM7, 0.0f);
  }
  int32_t map0_id() const {
    return GetField<int32_t>(VT_MAP0_ID, 0);
  }
  const ::flatbuffers::String *map0_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP0_NAME);
  }
  int32_t map1_id() const {
    return GetField<int32_t>(VT_MAP1_ID, 0);
  }
  const ::flatbuffers::String *map1_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP1_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<float>(verifier, VT_PARAM0, 4) &&
           VerifyField<float>(verifier, VT_PARAM1, 4) &&
           VerifyField<float>(verifier, VT_PARAM2, 4) &&
           VerifyField<float>(verifier, VT_PARAM3, 4) &&
           VerifyField<float>(verifier, VT_PARAM4, 4) &&
           VerifyField<float>(verifier, VT_PARAM5, 4) &&
           VerifyField<float>(verifier, VT_PARAM6, 4) &&
           VerifyField<float>(verifier, VT_PARAM7, 4) &&
           VerifyField<int32_t>(verifier, VT_MAP0_ID, 4) &&
           VerifyOffset(verifier, VT_MAP0_NAME) &&
           verifier.VerifyString(map0_name()) &&
           VerifyField<int32_t>(verifier, VT_MAP1_ID, 4) &&
           VerifyOffset(verifier, VT_MAP1_NAME) &&
           verifier.VerifyString(map1_name()) &&
           verifier.EndTable();
  }
};

struct PartAttributeShaderBuilder {
  typedef PartAttributeShader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(PartAttributeShader::VT_ID, id);
  }
  void add_param0(float param0) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM0, param0, 0.0f);
  }
  void add_param1(float param1) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM1, param1, 0.0f);
  }
  void add_param2(float param2) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM2, param2, 0.0f);
  }
  void add_param3(float param3) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM3, param3, 0.0f);
  }
  void add_param4(float param4) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM4, param4, 0.0f);
  }
  void add_param5(float param5) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM5, param5, 0.0f);
  }
  void add_param6(float param6) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM6, param6, 0.0f);
  }
  void add_param7(float param7) {
    fbb_.AddElement<float>(PartAttributeShader::VT_PARAM7, param7, 0.0f);
  }
  void add_map0_id(int32_t map0_id) {
    fbb_.AddElement<int32_t>(PartAttributeShader::VT_MAP0_ID, map0_id, 0);
  }
  void add_map0_name(::flatbuffers::Offset<::flatbuffers::String> map0_name) {
    fbb_.AddOffset(PartAttributeShader::VT_MAP0_NAME, map0_name);
  }
  void add_map1_id(int32_t map1_id) {
    fbb_.AddElement<int32_t>(PartAttributeShader::VT_MAP1_ID, map1_id, 0);
  }
  void add_map1_name(::flatbuffers::Offset<::flatbuffers::String> map1_name) {
    fbb_.AddOffset(PartAttributeShader::VT_MAP1_NAME, map1_name);
  }
  explicit PartAttributeShaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeShader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeShader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeShader> CreatePartAttributeShader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    float param0 = 0.0f,
    float param1 = 0.0f,
    float param2 = 0.0f,
    float param3 = 0.0f,
    float param4 = 0.0f,
    float param5 = 0.0f,
    float param6 = 0.0f,
    float param7 = 0.0f,
    int32_t map0_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map0_name = 0,
    int32_t map1_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map1_name = 0) {
  PartAttributeShaderBuilder builder_(_fbb);
  builder_.add_map1_name(map1_name);
  builder_.add_map1_id(map1_id);
  builder_.add_map0_name(map0_name);
  builder_.add_map0_id(map0_id);
  builder_.add_param7(param7);
  builder_.add_param6(param6);
  builder_.add_param5(param5);
  builder_.add_param4(param4);
  builder_.add_param3(param3);
  builder_.add_param2(param2);
  builder_.add_param1(param1);
  builder_.add_param0(param0);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeShader> CreatePartAttributeShaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    float param0 = 0.0f,
    float param1 = 0.0f,
    float param2 = 0.0f,
    float param3 = 0.0f,
    float param4 = 0.0f,
    float param5 = 0.0f,
    float param6 = 0.0f,
    float param7 = 0.0f,
    int32_t map0_id = 0,
    const char *map0_name = nullptr,
    int32_t map1_id = 0,
    const char *map1_name = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto map0_name__ = map0_name ? _fbb.CreateString(map0_name) : 0;
  auto map1_name__ = map1_name ? _fbb.CreateString(map1_name) : 0;
  return ss::runtime::CreatePartAttributeShader(
      _fbb,
      id__,
      param0,
      param1,
      param2,
      param3,
      param4,
      param5,
      param6,
      param7,
      map0_id,
      map0_name__,
      map1_id,
      map1_name__);
}

struct PartAttributeUserData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeUserDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTEGER = 4,
    VT_RECT = 6,
    VT_POINT = 8,
    VT_STR = 10
  };
  const ss::runtime::IntValueEntry *integer() const {
    return GetPointer<const ss::runtime::IntValueEntry *>(VT_INTEGER);
  }
  const ss::runtime::Rect *rect() const {
    return GetStruct<const ss::runtime::Rect *>(VT_RECT);
  }
  const ss::runtime::Vec2 *point() const {
    return GetStruct<const ss::runtime::Vec2 *>(VT_POINT);
  }
  const ::flatbuffers::String *str() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INTEGER) &&
           verifier.VerifyTable(integer()) &&
           VerifyField<ss::runtime::Rect>(verifier, VT_RECT, 4) &&
           VerifyField<ss::runtime::Vec2>(verifier, VT_POINT, 4) &&
           VerifyOffset(verifier, VT_STR) &&
           verifier.VerifyString(str()) &&
           verifier.EndTable();
  }
};

struct PartAttributeUserDataBuilder {
  typedef PartAttributeUserData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_integer(::flatbuffers::Offset<ss::runtime::IntValueEntry> integer) {
    fbb_.AddOffset(PartAttributeUserData::VT_INTEGER, integer);
  }
  void add_rect(const ss::runtime::Rect *rect) {
    fbb_.AddStruct(PartAttributeUserData::VT_RECT, rect);
  }
  void add_point(const ss::runtime::Vec2 *point) {
    fbb_.AddStruct(PartAttributeUserData::VT_POINT, point);
  }
  void add_str(::flatbuffers::Offset<::flatbuffers::String> str) {
    fbb_.AddOffset(PartAttributeUserData::VT_STR, str);
  }
  explicit PartAttributeUserDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeUserData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeUserData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeUserData> CreatePartAttributeUserData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ss::runtime::IntValueEntry> integer = 0,
    const ss::runtime::Rect *rect = nullptr,
    const ss::runtime::Vec2 *point = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> str = 0) {
  PartAttributeUserDataBuilder builder_(_fbb);
  builder_.add_str(str);
  builder_.add_point(point);
  builder_.add_rect(rect);
  builder_.add_integer(integer);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeUserData> CreatePartAttributeUserDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ss::runtime::IntValueEntry> integer = 0,
    const ss::runtime::Rect *rect = nullptr,
    const ss::runtime::Vec2 *point = nullptr,
    const char *str = nullptr) {
  auto str__ = str ? _fbb.CreateString(str) : 0;
  return ss::runtime::CreatePartAttributeUserData(
      _fbb,
      integer,
      rect,
      point,
      str__);
}

struct SignalCommandParam FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SignalCommandParamBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARAM_ID = 4,
    VT_TYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *param_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PARAM_ID);
  }
  ss::runtime::SignalCommandParamType type() const {
    return static_cast<ss::runtime::SignalCommandParamType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARAM_ID) &&
           verifier.VerifyString(param_id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct SignalCommandParamBuilder {
  typedef SignalCommandParam Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_param_id(::flatbuffers::Offset<::flatbuffers::String> param_id) {
    fbb_.AddOffset(SignalCommandParam::VT_PARAM_ID, param_id);
  }
  void add_type(ss::runtime::SignalCommandParamType type) {
    fbb_.AddElement<uint8_t>(SignalCommandParam::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(SignalCommandParam::VT_VALUE, value, 0.0f);
  }
  explicit SignalCommandParamBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SignalCommandParam> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SignalCommandParam>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SignalCommandParam> CreateSignalCommandParam(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> param_id = 0,
    ss::runtime::SignalCommandParamType type = ss::runtime::SignalCommandParamType_Index,
    float value = 0.0f) {
  SignalCommandParamBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_param_id(param_id);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SignalCommandParam> CreateSignalCommandParamDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *param_id = nullptr,
    ss::runtime::SignalCommandParamType type = ss::runtime::SignalCommandParamType_Index,
    float value = 0.0f) {
  auto param_id__ = param_id ? _fbb.CreateString(param_id) : 0;
  return ss::runtime::CreateSignalCommandParam(
      _fbb,
      param_id__,
      type,
      value);
}

struct PartAttributeSignal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeSignalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTIVE = 4,
    VT_COMMAND_ID = 6,
    VT_PARAMS = 8
  };
  bool active() const {
    return GetField<uint8_t>(VT_ACTIVE, 0) != 0;
  }
  const ::flatbuffers::String *command_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMMAND_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>> *params() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>> *>(VT_PARAMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVE, 1) &&
           VerifyOffset(verifier, VT_COMMAND_ID) &&
           verifier.VerifyString(command_id()) &&
           VerifyOffset(verifier, VT_PARAMS) &&
           verifier.VerifyVector(params()) &&
           verifier.VerifyVectorOfTables(params()) &&
           verifier.EndTable();
  }
};

struct PartAttributeSignalBuilder {
  typedef PartAttributeSignal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_active(bool active) {
    fbb_.AddElement<uint8_t>(PartAttributeSignal::VT_ACTIVE, static_cast<uint8_t>(active), 0);
  }
  void add_command_id(::flatbuffers::Offset<::flatbuffers::String> command_id) {
    fbb_.AddOffset(PartAttributeSignal::VT_COMMAND_ID, command_id);
  }
  void add_params(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>>> params) {
    fbb_.AddOffset(PartAttributeSignal::VT_PARAMS, params);
  }
  explicit PartAttributeSignalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeSignal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeSignal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeSignal> CreatePartAttributeSignal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool active = false,
    ::flatbuffers::Offset<::flatbuffers::String> command_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>>> params = 0) {
  PartAttributeSignalBuilder builder_(_fbb);
  builder_.add_params(params);
  builder_.add_command_id(command_id);
  builder_.add_active(active);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeSignal> CreatePartAttributeSignalDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool active = false,
    const char *command_id = nullptr,
    const std::vector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>> *params = nullptr) {
  auto command_id__ = command_id ? _fbb.CreateString(command_id) : 0;
  auto params__ = params ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::SignalCommandParam>>(*params) : 0;
  return ss::runtime::CreatePartAttributeSignal(
      _fbb,
      active,
      command_id__,
      params__);
}

struct PartAttributeAudio FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeAudioBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOUND_LIST_ID = 4,
    VT_SOUND_NAME = 6,
    VT_LOOP_NUM = 8
  };
  int32_t sound_list_id() const {
    return GetField<int32_t>(VT_SOUND_LIST_ID, 0);
  }
  const ::flatbuffers::String *sound_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOUND_NAME);
  }
  int32_t loop_num() const {
    return GetField<int32_t>(VT_LOOP_NUM, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SOUND_LIST_ID, 4) &&
           VerifyOffset(verifier, VT_SOUND_NAME) &&
           verifier.VerifyString(sound_name()) &&
           VerifyField<int32_t>(verifier, VT_LOOP_NUM, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributeAudioBuilder {
  typedef PartAttributeAudio Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sound_list_id(int32_t sound_list_id) {
    fbb_.AddElement<int32_t>(PartAttributeAudio::VT_SOUND_LIST_ID, sound_list_id, 0);
  }
  void add_sound_name(::flatbuffers::Offset<::flatbuffers::String> sound_name) {
    fbb_.AddOffset(PartAttributeAudio::VT_SOUND_NAME, sound_name);
  }
  void add_loop_num(int32_t loop_num) {
    fbb_.AddElement<int32_t>(PartAttributeAudio::VT_LOOP_NUM, loop_num, 0);
  }
  explicit PartAttributeAudioBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeAudio> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeAudio>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeAudio> CreatePartAttributeAudio(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t sound_list_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sound_name = 0,
    int32_t loop_num = 0) {
  PartAttributeAudioBuilder builder_(_fbb);
  builder_.add_loop_num(loop_num);
  builder_.add_sound_name(sound_name);
  builder_.add_sound_list_id(sound_list_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeAudio> CreatePartAttributeAudioDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t sound_list_id = 0,
    const char *sound_name = nullptr,
    int32_t loop_num = 0) {
  auto sound_name__ = sound_name ? _fbb.CreateString(sound_name) : 0;
  return ss::runtime::CreatePartAttributeAudio(
      _fbb,
      sound_list_id,
      sound_name__,
      loop_num);
}

struct PartAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CELL = 4,
    VT_POSITION_X = 6,
    VT_POSITION_Y = 8,
    VT_POSITION_Z = 10,
    VT_ROTATION_X = 12,
    VT_ROTATION_Y = 14,
    VT_ROTATION_Z = 16,
    VT_SCALE_X = 18,
    VT_SCALE_Y = 20,
    VT_LOCAL_SCALE_X = 22,
    VT_LOCAL_SCALE_Y = 24,
    VT_OPACITY = 26,
    VT_LOCALOPACITY = 28,
    VT_PRIORITY = 30,
    VT_FLIP_V = 32,
    VT_FLIP_H = 34,
    VT_HIDE = 36,
    VT_PARTS_COLOR = 38,
    VT_SHADER = 40,
    VT_VERTEX = 42,
    VT_PIVOT_X = 44,
    VT_PIVOT_Y = 46,
    VT_ANCHOR_X = 48,
    VT_ANCHOR_Y = 50,
    VT_SIZE_X = 52,
    VT_SIZE_Y = 54,
    VT_IMG_FLIP_H = 56,
    VT_IMG_FLIP_V = 58,
    VT_UV_MOVE_X = 60,
    VT_UV_MOVE_Y = 62,
    VT_UV_MOVE_Z = 64,
    VT_UV_SCALE_X = 66,
    VT_UV_SCALE_Y = 68,
    VT_BOUNDING_RADIUS = 70,
    VT_MASK = 72,
    VT_SKEW_X = 74,
    VT_SKEW_Y = 76,
    VT_DEFORM = 78,
    VT_TEXTURE = 80
  };
  const ss::runtime::PartAttributeCell *cell() const {
    return GetPointer<const ss::runtime::PartAttributeCell *>(VT_CELL);
  }
  float position_x() const {
    return GetField<float>(VT_POSITION_X, 0.0f);
  }
  float position_y() const {
    return GetField<float>(VT_POSITION_Y, 0.0f);
  }
  float position_z() const {
    return GetField<float>(VT_POSITION_Z, 0.0f);
  }
  float rotation_x() const {
    return GetField<float>(VT_ROTATION_X, 0.0f);
  }
  float rotation_y() const {
    return GetField<float>(VT_ROTATION_Y, 0.0f);
  }
  float rotation_z() const {
    return GetField<float>(VT_ROTATION_Z, 0.0f);
  }
  float scale_x() const {
    return GetField<float>(VT_SCALE_X, 1.0f);
  }
  float scale_y() const {
    return GetField<float>(VT_SCALE_Y, 1.0f);
  }
  float local_scale_x() const {
    return GetField<float>(VT_LOCAL_SCALE_X, 1.0f);
  }
  float local_scale_y() const {
    return GetField<float>(VT_LOCAL_SCALE_Y, 1.0f);
  }
  float opacity() const {
    return GetField<float>(VT_OPACITY, 1.0f);
  }
  float localopacity() const {
    return GetField<float>(VT_LOCALOPACITY, 1.0f);
  }
  float priority() const {
    return GetField<float>(VT_PRIORITY, 0.0f);
  }
  bool flip_v() const {
    return GetField<uint8_t>(VT_FLIP_V, 0) != 0;
  }
  bool flip_h() const {
    return GetField<uint8_t>(VT_FLIP_H, 0) != 0;
  }
  bool hide() const {
    return GetField<uint8_t>(VT_HIDE, 0) != 0;
  }
  const ss::runtime::PartAttributePartColor *parts_color() const {
    return GetPointer<const ss::runtime::PartAttributePartColor *>(VT_PARTS_COLOR);
  }
  const ss::runtime::PartAttributeShader *shader() const {
    return GetPointer<const ss::runtime::PartAttributeShader *>(VT_SHADER);
  }
  const ss::runtime::PartAttributeVertex *vertex() const {
    return GetPointer<const ss::runtime::PartAttributeVertex *>(VT_VERTEX);
  }
  float pivot_x() const {
    return GetField<float>(VT_PIVOT_X, 0.0f);
  }
  float pivot_y() const {
    return GetField<float>(VT_PIVOT_Y, 0.0f);
  }
  float anchor_x() const {
    return GetField<float>(VT_ANCHOR_X, 0.0f);
  }
  float anchor_y() const {
    return GetField<float>(VT_ANCHOR_Y, 0.0f);
  }
  float size_x() const {
    return GetField<float>(VT_SIZE_X, 1.0f);
  }
  float size_y() const {
    return GetField<float>(VT_SIZE_Y, 1.0f);
  }
  bool img_flip_h() const {
    return GetField<uint8_t>(VT_IMG_FLIP_H, 0) != 0;
  }
  bool img_flip_v() const {
    return GetField<uint8_t>(VT_IMG_FLIP_V, 0) != 0;
  }
  float uv_move_x() const {
    return GetField<float>(VT_UV_MOVE_X, 0.0f);
  }
  float uv_move_y() const {
    return GetField<float>(VT_UV_MOVE_Y, 0.0f);
  }
  float uv_move_z() const {
    return GetField<float>(VT_UV_MOVE_Z, 0.0f);
  }
  float uv_scale_x() const {
    return GetField<float>(VT_UV_SCALE_X, 1.0f);
  }
  float uv_scale_y() const {
    return GetField<float>(VT_UV_SCALE_Y, 1.0f);
  }
  float bounding_radius() const {
    return GetField<float>(VT_BOUNDING_RADIUS, 0.0f);
  }
  float mask() const {
    return GetField<float>(VT_MASK, 0.0f);
  }
  float skew_x() const {
    return GetField<float>(VT_SKEW_X, 0.0f);
  }
  float skew_y() const {
    return GetField<float>(VT_SKEW_Y, 0.0f);
  }
  const ss::runtime::PartAttributeDeform *deform() const {
    return GetPointer<const ss::runtime::PartAttributeDeform *>(VT_DEFORM);
  }
  int32_t texture() const {
    return GetField<int32_t>(VT_TEXTURE, -1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CELL) &&
           verifier.VerifyTable(cell()) &&
           VerifyField<float>(verifier, VT_POSITION_X, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Y, 4) &&
           VerifyField<float>(verifier, VT_POSITION_Z, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_X, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_Y, 4) &&
           VerifyField<float>(verifier, VT_ROTATION_Z, 4) &&
           VerifyField<float>(verifier, VT_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_LOCAL_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_LOCAL_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_OPACITY, 4) &&
           VerifyField<float>(verifier, VT_LOCALOPACITY, 4) &&
           VerifyField<float>(verifier, VT_PRIORITY, 4) &&
           VerifyField<uint8_t>(verifier, VT_FLIP_V, 1) &&
           VerifyField<uint8_t>(verifier, VT_FLIP_H, 1) &&
           VerifyField<uint8_t>(verifier, VT_HIDE, 1) &&
           VerifyOffset(verifier, VT_PARTS_COLOR) &&
           verifier.VerifyTable(parts_color()) &&
           VerifyOffset(verifier, VT_SHADER) &&
           verifier.VerifyTable(shader()) &&
           VerifyOffset(verifier, VT_VERTEX) &&
           verifier.VerifyTable(vertex()) &&
           VerifyField<float>(verifier, VT_PIVOT_X, 4) &&
           VerifyField<float>(verifier, VT_PIVOT_Y, 4) &&
           VerifyField<float>(verifier, VT_ANCHOR_X, 4) &&
           VerifyField<float>(verifier, VT_ANCHOR_Y, 4) &&
           VerifyField<float>(verifier, VT_SIZE_X, 4) &&
           VerifyField<float>(verifier, VT_SIZE_Y, 4) &&
           VerifyField<uint8_t>(verifier, VT_IMG_FLIP_H, 1) &&
           VerifyField<uint8_t>(verifier, VT_IMG_FLIP_V, 1) &&
           VerifyField<float>(verifier, VT_UV_MOVE_X, 4) &&
           VerifyField<float>(verifier, VT_UV_MOVE_Y, 4) &&
           VerifyField<float>(verifier, VT_UV_MOVE_Z, 4) &&
           VerifyField<float>(verifier, VT_UV_SCALE_X, 4) &&
           VerifyField<float>(verifier, VT_UV_SCALE_Y, 4) &&
           VerifyField<float>(verifier, VT_BOUNDING_RADIUS, 4) &&
           VerifyField<float>(verifier, VT_MASK, 4) &&
           VerifyField<float>(verifier, VT_SKEW_X, 4) &&
           VerifyField<float>(verifier, VT_SKEW_Y, 4) &&
           VerifyOffset(verifier, VT_DEFORM) &&
           verifier.VerifyTable(deform()) &&
           VerifyField<int32_t>(verifier, VT_TEXTURE, 4) &&
           verifier.EndTable();
  }
};

struct PartAttributesBuilder {
  typedef PartAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cell(::flatbuffers::Offset<ss::runtime::PartAttributeCell> cell) {
    fbb_.AddOffset(PartAttributes::VT_CELL, cell);
  }
  void add_position_x(float position_x) {
    fbb_.AddElement<float>(PartAttributes::VT_POSITION_X, position_x, 0.0f);
  }
  void add_position_y(float position_y) {
    fbb_.AddElement<float>(PartAttributes::VT_POSITION_Y, position_y, 0.0f);
  }
  void add_position_z(float position_z) {
    fbb_.AddElement<float>(PartAttributes::VT_POSITION_Z, position_z, 0.0f);
  }
  void add_rotation_x(float rotation_x) {
    fbb_.AddElement<float>(PartAttributes::VT_ROTATION_X, rotation_x, 0.0f);
  }
  void add_rotation_y(float rotation_y) {
    fbb_.AddElement<float>(PartAttributes::VT_ROTATION_Y, rotation_y, 0.0f);
  }
  void add_rotation_z(float rotation_z) {
    fbb_.AddElement<float>(PartAttributes::VT_ROTATION_Z, rotation_z, 0.0f);
  }
  void add_scale_x(float scale_x) {
    fbb_.AddElement<float>(PartAttributes::VT_SCALE_X, scale_x, 1.0f);
  }
  void add_scale_y(float scale_y) {
    fbb_.AddElement<float>(PartAttributes::VT_SCALE_Y, scale_y, 1.0f);
  }
  void add_local_scale_x(float local_scale_x) {
    fbb_.AddElement<float>(PartAttributes::VT_LOCAL_SCALE_X, local_scale_x, 1.0f);
  }
  void add_local_scale_y(float local_scale_y) {
    fbb_.AddElement<float>(PartAttributes::VT_LOCAL_SCALE_Y, local_scale_y, 1.0f);
  }
  void add_opacity(float opacity) {
    fbb_.AddElement<float>(PartAttributes::VT_OPACITY, opacity, 1.0f);
  }
  void add_localopacity(float localopacity) {
    fbb_.AddElement<float>(PartAttributes::VT_LOCALOPACITY, localopacity, 1.0f);
  }
  void add_priority(float priority) {
    fbb_.AddElement<float>(PartAttributes::VT_PRIORITY, priority, 0.0f);
  }
  void add_flip_v(bool flip_v) {
    fbb_.AddElement<uint8_t>(PartAttributes::VT_FLIP_V, static_cast<uint8_t>(flip_v), 0);
  }
  void add_flip_h(bool flip_h) {
    fbb_.AddElement<uint8_t>(PartAttributes::VT_FLIP_H, static_cast<uint8_t>(flip_h), 0);
  }
  void add_hide(bool hide) {
    fbb_.AddElement<uint8_t>(PartAttributes::VT_HIDE, static_cast<uint8_t>(hide), 0);
  }
  void add_parts_color(::flatbuffers::Offset<ss::runtime::PartAttributePartColor> parts_color) {
    fbb_.AddOffset(PartAttributes::VT_PARTS_COLOR, parts_color);
  }
  void add_shader(::flatbuffers::Offset<ss::runtime::PartAttributeShader> shader) {
    fbb_.AddOffset(PartAttributes::VT_SHADER, shader);
  }
  void add_vertex(::flatbuffers::Offset<ss::runtime::PartAttributeVertex> vertex) {
    fbb_.AddOffset(PartAttributes::VT_VERTEX, vertex);
  }
  void add_pivot_x(float pivot_x) {
    fbb_.AddElement<float>(PartAttributes::VT_PIVOT_X, pivot_x, 0.0f);
  }
  void add_pivot_y(float pivot_y) {
    fbb_.AddElement<float>(PartAttributes::VT_PIVOT_Y, pivot_y, 0.0f);
  }
  void add_anchor_x(float anchor_x) {
    fbb_.AddElement<float>(PartAttributes::VT_ANCHOR_X, anchor_x, 0.0f);
  }
  void add_anchor_y(float anchor_y) {
    fbb_.AddElement<float>(PartAttributes::VT_ANCHOR_Y, anchor_y, 0.0f);
  }
  void add_size_x(float size_x) {
    fbb_.AddElement<float>(PartAttributes::VT_SIZE_X, size_x, 1.0f);
  }
  void add_size_y(float size_y) {
    fbb_.AddElement<float>(PartAttributes::VT_SIZE_Y, size_y, 1.0f);
  }
  void add_img_flip_h(bool img_flip_h) {
    fbb_.AddElement<uint8_t>(PartAttributes::VT_IMG_FLIP_H, static_cast<uint8_t>(img_flip_h), 0);
  }
  void add_img_flip_v(bool img_flip_v) {
    fbb_.AddElement<uint8_t>(PartAttributes::VT_IMG_FLIP_V, static_cast<uint8_t>(img_flip_v), 0);
  }
  void add_uv_move_x(float uv_move_x) {
    fbb_.AddElement<float>(PartAttributes::VT_UV_MOVE_X, uv_move_x, 0.0f);
  }
  void add_uv_move_y(float uv_move_y) {
    fbb_.AddElement<float>(PartAttributes::VT_UV_MOVE_Y, uv_move_y, 0.0f);
  }
  void add_uv_move_z(float uv_move_z) {
    fbb_.AddElement<float>(PartAttributes::VT_UV_MOVE_Z, uv_move_z, 0.0f);
  }
  void add_uv_scale_x(float uv_scale_x) {
    fbb_.AddElement<float>(PartAttributes::VT_UV_SCALE_X, uv_scale_x, 1.0f);
  }
  void add_uv_scale_y(float uv_scale_y) {
    fbb_.AddElement<float>(PartAttributes::VT_UV_SCALE_Y, uv_scale_y, 1.0f);
  }
  void add_bounding_radius(float bounding_radius) {
    fbb_.AddElement<float>(PartAttributes::VT_BOUNDING_RADIUS, bounding_radius, 0.0f);
  }
  void add_mask(float mask) {
    fbb_.AddElement<float>(PartAttributes::VT_MASK, mask, 0.0f);
  }
  void add_skew_x(float skew_x) {
    fbb_.AddElement<float>(PartAttributes::VT_SKEW_X, skew_x, 0.0f);
  }
  void add_skew_y(float skew_y) {
    fbb_.AddElement<float>(PartAttributes::VT_SKEW_Y, skew_y, 0.0f);
  }
  void add_deform(::flatbuffers::Offset<ss::runtime::PartAttributeDeform> deform) {
    fbb_.AddOffset(PartAttributes::VT_DEFORM, deform);
  }
  void add_texture(int32_t texture) {
    fbb_.AddElement<int32_t>(PartAttributes::VT_TEXTURE, texture, -1);
  }
  explicit PartAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributes> CreatePartAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ss::runtime::PartAttributeCell> cell = 0,
    float position_x = 0.0f,
    float position_y = 0.0f,
    float position_z = 0.0f,
    float rotation_x = 0.0f,
    float rotation_y = 0.0f,
    float rotation_z = 0.0f,
    float scale_x = 1.0f,
    float scale_y = 1.0f,
    float local_scale_x = 1.0f,
    float local_scale_y = 1.0f,
    float opacity = 1.0f,
    float localopacity = 1.0f,
    float priority = 0.0f,
    bool flip_v = false,
    bool flip_h = false,
    bool hide = false,
    ::flatbuffers::Offset<ss::runtime::PartAttributePartColor> parts_color = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeShader> shader = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeVertex> vertex = 0,
    float pivot_x = 0.0f,
    float pivot_y = 0.0f,
    float anchor_x = 0.0f,
    float anchor_y = 0.0f,
    float size_x = 1.0f,
    float size_y = 1.0f,
    bool img_flip_h = false,
    bool img_flip_v = false,
    float uv_move_x = 0.0f,
    float uv_move_y = 0.0f,
    float uv_move_z = 0.0f,
    float uv_scale_x = 1.0f,
    float uv_scale_y = 1.0f,
    float bounding_radius = 0.0f,
    float mask = 0.0f,
    float skew_x = 0.0f,
    float skew_y = 0.0f,
    ::flatbuffers::Offset<ss::runtime::PartAttributeDeform> deform = 0,
    int32_t texture = -1) {
  PartAttributesBuilder builder_(_fbb);
  builder_.add_texture(texture);
  builder_.add_deform(deform);
  builder_.add_skew_y(skew_y);
  builder_.add_skew_x(skew_x);
  builder_.add_mask(mask);
  builder_.add_bounding_radius(bounding_radius);
  builder_.add_uv_scale_y(uv_scale_y);
  builder_.add_uv_scale_x(uv_scale_x);
  builder_.add_uv_move_z(uv_move_z);
  builder_.add_uv_move_y(uv_move_y);
  builder_.add_uv_move_x(uv_move_x);
  builder_.add_size_y(size_y);
  builder_.add_size_x(size_x);
  builder_.add_anchor_y(anchor_y);
  builder_.add_anchor_x(anchor_x);
  builder_.add_pivot_y(pivot_y);
  builder_.add_pivot_x(pivot_x);
  builder_.add_vertex(vertex);
  builder_.add_shader(shader);
  builder_.add_parts_color(parts_color);
  builder_.add_priority(priority);
  builder_.add_localopacity(localopacity);
  builder_.add_opacity(opacity);
  builder_.add_local_scale_y(local_scale_y);
  builder_.add_local_scale_x(local_scale_x);
  builder_.add_scale_y(scale_y);
  builder_.add_scale_x(scale_x);
  builder_.add_rotation_z(rotation_z);
  builder_.add_rotation_y(rotation_y);
  builder_.add_rotation_x(rotation_x);
  builder_.add_position_z(position_z);
  builder_.add_position_y(position_y);
  builder_.add_position_x(position_x);
  builder_.add_cell(cell);
  builder_.add_img_flip_v(img_flip_v);
  builder_.add_img_flip_h(img_flip_h);
  builder_.add_hide(hide);
  builder_.add_flip_h(flip_h);
  builder_.add_flip_v(flip_v);
  return builder_.Finish();
}

struct PartMeshData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartMeshDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_UV = 6,
    VT_INDICES = 8,
    VT_COUNT_COORDINATE_MESH = 10,
    VT_INDEX_COORDINATE_DEFORM = 12
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  const ::flatbuffers::Vector<float> *uv() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_UV);
  }
  const ::flatbuffers::Vector<int32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_INDICES);
  }
  int32_t count_coordinate_mesh() const {
    return GetField<int32_t>(VT_COUNT_COORDINATE_MESH, 0);
  }
  const ::flatbuffers::Vector<int32_t> *index_coordinate_deform() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_INDEX_COORDINATE_DEFORM);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_UV) &&
           verifier.VerifyVector(uv()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyField<int32_t>(verifier, VT_COUNT_COORDINATE_MESH, 4) &&
           VerifyOffset(verifier, VT_INDEX_COORDINATE_DEFORM) &&
           verifier.VerifyVector(index_coordinate_deform()) &&
           verifier.EndTable();
  }
};

struct PartMeshDataBuilder {
  typedef PartMeshData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(PartMeshData::VT_PART_INDEX, part_index, 0);
  }
  void add_uv(::flatbuffers::Offset<::flatbuffers::Vector<float>> uv) {
    fbb_.AddOffset(PartMeshData::VT_UV, uv);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> indices) {
    fbb_.AddOffset(PartMeshData::VT_INDICES, indices);
  }
  void add_count_coordinate_mesh(int32_t count_coordinate_mesh) {
    fbb_.AddElement<int32_t>(PartMeshData::VT_COUNT_COORDINATE_MESH, count_coordinate_mesh, 0);
  }
  void add_index_coordinate_deform(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> index_coordinate_deform) {
    fbb_.AddOffset(PartMeshData::VT_INDEX_COORDINATE_DEFORM, index_coordinate_deform);
  }
  explicit PartMeshDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartMeshData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartMeshData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartMeshData> CreatePartMeshData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> uv = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> indices = 0,
    int32_t count_coordinate_mesh = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> index_coordinate_deform = 0) {
  PartMeshDataBuilder builder_(_fbb);
  builder_.add_index_coordinate_deform(index_coordinate_deform);
  builder_.add_count_coordinate_mesh(count_coordinate_mesh);
  builder_.add_indices(indices);
  builder_.add_uv(uv);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartMeshData> CreatePartMeshDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    const std::vector<float> *uv = nullptr,
    const std::vector<int32_t> *indices = nullptr,
    int32_t count_coordinate_mesh = 0,
    const std::vector<int32_t> *index_coordinate_deform = nullptr) {
  auto uv__ = uv ? _fbb.CreateVector<float>(*uv) : 0;
  auto indices__ = indices ? _fbb.CreateVector<int32_t>(*indices) : 0;
  auto index_coordinate_deform__ = index_coordinate_deform ? _fbb.CreateVector<int32_t>(*index_coordinate_deform) : 0;
  return ss::runtime::CreatePartMeshData(
      _fbb,
      part_index,
      uv__,
      indices__,
      count_coordinate_mesh,
      index_coordinate_deform__);
}

struct EventUserData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventUserDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_VALUE = 6
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventUserData * const o) const {
    return part_index() < o->part_index();
  }
  int KeyCompareWithValue(uint16_t _part_index) const {
    return static_cast<int>(part_index() > _part_index) - static_cast<int>(part_index() < _part_index);
  }
  const ss::runtime::PartAttributeUserData *value() const {
    return GetPointer<const ss::runtime::PartAttributeUserData *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct EventUserDataBuilder {
  typedef EventUserData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(EventUserData::VT_PART_INDEX, part_index, 0);
  }
  void add_value(::flatbuffers::Offset<ss::runtime::PartAttributeUserData> value) {
    fbb_.AddOffset(EventUserData::VT_VALUE, value);
  }
  explicit EventUserDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventUserData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventUserData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventUserData> CreateEventUserData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeUserData> value = 0) {
  EventUserDataBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

struct EventSignal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventSignalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_VALUE = 6
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventSignal * const o) const {
    return part_index() < o->part_index();
  }
  int KeyCompareWithValue(uint16_t _part_index) const {
    return static_cast<int>(part_index() > _part_index) - static_cast<int>(part_index() < _part_index);
  }
  const ss::runtime::PartAttributeSignal *value() const {
    return GetPointer<const ss::runtime::PartAttributeSignal *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct EventSignalBuilder {
  typedef EventSignal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(EventSignal::VT_PART_INDEX, part_index, 0);
  }
  void add_value(::flatbuffers::Offset<ss::runtime::PartAttributeSignal> value) {
    fbb_.AddOffset(EventSignal::VT_VALUE, value);
  }
  explicit EventSignalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventSignal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventSignal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventSignal> CreateEventSignal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeSignal> value = 0) {
  EventSignalBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

struct EventAudio FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventAudioBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_VALUE = 6
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventAudio * const o) const {
    return part_index() < o->part_index();
  }
  int KeyCompareWithValue(uint16_t _part_index) const {
    return static_cast<int>(part_index() > _part_index) - static_cast<int>(part_index() < _part_index);
  }
  const ss::runtime::PartAttributeAudio *value() const {
    return GetPointer<const ss::runtime::PartAttributeAudio *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct EventAudioBuilder {
  typedef EventAudio Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(EventAudio::VT_PART_INDEX, part_index, 0);
  }
  void add_value(::flatbuffers::Offset<ss::runtime::PartAttributeAudio> value) {
    fbb_.AddOffset(EventAudio::VT_VALUE, value);
  }
  explicit EventAudioBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventAudio> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventAudio>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventAudio> CreateEventAudio(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeAudio> value = 0) {
  EventAudioBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

struct EventInstance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventInstanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_VALUE = 6
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventInstance * const o) const {
    return part_index() < o->part_index();
  }
  int KeyCompareWithValue(uint16_t _part_index) const {
    return static_cast<int>(part_index() > _part_index) - static_cast<int>(part_index() < _part_index);
  }
  const ss::runtime::PartAttributeInstance *value() const {
    return GetPointer<const ss::runtime::PartAttributeInstance *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct EventInstanceBuilder {
  typedef EventInstance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(EventInstance::VT_PART_INDEX, part_index, 0);
  }
  void add_value(::flatbuffers::Offset<ss::runtime::PartAttributeInstance> value) {
    fbb_.AddOffset(EventInstance::VT_VALUE, value);
  }
  explicit EventInstanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventInstance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventInstance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventInstance> CreateEventInstance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeInstance> value = 0) {
  EventInstanceBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

struct EventEffect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventEffectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PART_INDEX = 4,
    VT_VALUE = 6
  };
  uint16_t part_index() const {
    return GetField<uint16_t>(VT_PART_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventEffect * const o) const {
    return part_index() < o->part_index();
  }
  int KeyCompareWithValue(uint16_t _part_index) const {
    return static_cast<int>(part_index() > _part_index) - static_cast<int>(part_index() < _part_index);
  }
  const ss::runtime::PartAttributeEffect *value() const {
    return GetPointer<const ss::runtime::PartAttributeEffect *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_PART_INDEX, 2) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct EventEffectBuilder {
  typedef EventEffect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_part_index(uint16_t part_index) {
    fbb_.AddElement<uint16_t>(EventEffect::VT_PART_INDEX, part_index, 0);
  }
  void add_value(::flatbuffers::Offset<ss::runtime::PartAttributeEffect> value) {
    fbb_.AddOffset(EventEffect::VT_VALUE, value);
  }
  explicit EventEffectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventEffect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventEffect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventEffect> CreateEventEffect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t part_index = 0,
    ::flatbuffers::Offset<ss::runtime::PartAttributeEffect> value = 0) {
  EventEffectBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_part_index(part_index);
  return builder_.Finish();
}

struct EventsPerFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventsPerFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FRAME_INDEX = 4,
    VT_USERS = 6,
    VT_SIGNALS = 8,
    VT_AUDIOS = 10,
    VT_INSTANCES = 12,
    VT_EFFECTS = 14
  };
  uint16_t frame_index() const {
    return GetField<uint16_t>(VT_FRAME_INDEX, 0);
  }
  bool KeyCompareLessThan(const EventsPerFrame * const o) const {
    return frame_index() < o->frame_index();
  }
  int KeyCompareWithValue(uint16_t _frame_index) const {
    return static_cast<int>(frame_index() > _frame_index) - static_cast<int>(frame_index() < _frame_index);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventUserData>> *users() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventUserData>> *>(VT_USERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventSignal>> *signals() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventSignal>> *>(VT_SIGNALS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventAudio>> *audios() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventAudio>> *>(VT_AUDIOS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventInstance>> *instances() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventInstance>> *>(VT_INSTANCES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventEffect>> *effects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventEffect>> *>(VT_EFFECTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_FRAME_INDEX, 2) &&
           VerifyOffset(verifier, VT_USERS) &&
           verifier.VerifyVector(users()) &&
           verifier.VerifyVectorOfTables(users()) &&
           VerifyOffset(verifier, VT_SIGNALS) &&
           verifier.VerifyVector(signals()) &&
           verifier.VerifyVectorOfTables(signals()) &&
           VerifyOffset(verifier, VT_AUDIOS) &&
           verifier.VerifyVector(audios()) &&
           verifier.VerifyVectorOfTables(audios()) &&
           VerifyOffset(verifier, VT_INSTANCES) &&
           verifier.VerifyVector(instances()) &&
           verifier.VerifyVectorOfTables(instances()) &&
           VerifyOffset(verifier, VT_EFFECTS) &&
           verifier.VerifyVector(effects()) &&
           verifier.VerifyVectorOfTables(effects()) &&
           verifier.EndTable();
  }
};

struct EventsPerFrameBuilder {
  typedef EventsPerFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_frame_index(uint16_t frame_index) {
    fbb_.AddElement<uint16_t>(EventsPerFrame::VT_FRAME_INDEX, frame_index, 0);
  }
  void add_users(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventUserData>>> users) {
    fbb_.AddOffset(EventsPerFrame::VT_USERS, users);
  }
  void add_signals(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventSignal>>> signals) {
    fbb_.AddOffset(EventsPerFrame::VT_SIGNALS, signals);
  }
  void add_audios(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventAudio>>> audios) {
    fbb_.AddOffset(EventsPerFrame::VT_AUDIOS, audios);
  }
  void add_instances(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventInstance>>> instances) {
    fbb_.AddOffset(EventsPerFrame::VT_INSTANCES, instances);
  }
  void add_effects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventEffect>>> effects) {
    fbb_.AddOffset(EventsPerFrame::VT_EFFECTS, effects);
  }
  explicit EventsPerFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventsPerFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventsPerFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventsPerFrame> CreateEventsPerFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t frame_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventUserData>>> users = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventSignal>>> signals = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventAudio>>> audios = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventInstance>>> instances = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventEffect>>> effects = 0) {
  EventsPerFrameBuilder builder_(_fbb);
  builder_.add_effects(effects);
  builder_.add_instances(instances);
  builder_.add_audios(audios);
  builder_.add_signals(signals);
  builder_.add_users(users);
  builder_.add_frame_index(frame_index);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventsPerFrame> CreateEventsPerFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t frame_index = 0,
    std::vector<::flatbuffers::Offset<ss::runtime::EventUserData>> *users = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::EventSignal>> *signals = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::EventAudio>> *audios = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::EventInstance>> *instances = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::EventEffect>> *effects = nullptr) {
  auto users__ = users ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventUserData>(users) : 0;
  auto signals__ = signals ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventSignal>(signals) : 0;
  auto audios__ = audios ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventAudio>(audios) : 0;
  auto instances__ = instances ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventInstance>(instances) : 0;
  auto effects__ = effects ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventEffect>(effects) : 0;
  return ss::runtime::CreateEventsPerFrame(
      _fbb,
      frame_index,
      users__,
      signals__,
      audios__,
      instances__,
      effects__);
}

struct Label FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LabelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TIME = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const Label * const o) const {
    return *name() < *o->name();
  }
  int KeyCompareWithValue(const char *_name) const {
    return strcmp(name()->c_str(), _name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _name) const {
    if (name()->c_str() < _name) return -1;
    if (_name < name()->c_str()) return 1;
    return 0;
  }
  int32_t time() const {
    return GetField<int32_t>(VT_TIME, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_TIME, 4) &&
           verifier.EndTable();
  }
};

struct LabelBuilder {
  typedef Label Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Label::VT_NAME, name);
  }
  void add_time(int32_t time) {
    fbb_.AddElement<int32_t>(Label::VT_TIME, time, 0);
  }
  explicit LabelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Label> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Label>(end);
    fbb_.Required(o, Label::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Label> CreateLabel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t time = 0) {
  LabelBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Label> CreateLabelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t time = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ss::runtime::CreateLabel(
      _fbb,
      name__,
      time);
}

struct AnimPrepData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimPrepDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTS_INITIAL_ATTRIBUTES = 4,
    VT_PARTS_MESH_DATA = 6,
    VT_EVENTS = 8,
    VT_LABELS = 10,
    VT_START_FRAME = 12,
    VT_END_FRAME = 14,
    VT_TOTAL_FRAME = 16,
    VT_FPS = 18,
    VT_CANVAS = 20
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributes>> *parts_initial_attributes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributes>> *>(VT_PARTS_INITIAL_ATTRIBUTES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartMeshData>> *parts_mesh_data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartMeshData>> *>(VT_PARTS_MESH_DATA);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventsPerFrame>> *events() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventsPerFrame>> *>(VT_EVENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::Label>> *labels() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::Label>> *>(VT_LABELS);
  }
  int16_t start_frame() const {
    return GetField<int16_t>(VT_START_FRAME, 0);
  }
  int16_t end_frame() const {
    return GetField<int16_t>(VT_END_FRAME, 0);
  }
  int16_t total_frame() const {
    return GetField<int16_t>(VT_TOTAL_FRAME, 0);
  }
  int16_t fps() const {
    return GetField<int16_t>(VT_FPS, 0);
  }
  const ss::runtime::Rect *canvas() const {
    return GetStruct<const ss::runtime::Rect *>(VT_CANVAS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARTS_INITIAL_ATTRIBUTES) &&
           verifier.VerifyVector(parts_initial_attributes()) &&
           verifier.VerifyVectorOfTables(parts_initial_attributes()) &&
           VerifyOffset(verifier, VT_PARTS_MESH_DATA) &&
           verifier.VerifyVector(parts_mesh_data()) &&
           verifier.VerifyVectorOfTables(parts_mesh_data()) &&
           VerifyOffset(verifier, VT_EVENTS) &&
           verifier.VerifyVector(events()) &&
           verifier.VerifyVectorOfTables(events()) &&
           VerifyOffset(verifier, VT_LABELS) &&
           verifier.VerifyVector(labels()) &&
           verifier.VerifyVectorOfTables(labels()) &&
           VerifyField<int16_t>(verifier, VT_START_FRAME, 2) &&
           VerifyField<int16_t>(verifier, VT_END_FRAME, 2) &&
           VerifyField<int16_t>(verifier, VT_TOTAL_FRAME, 2) &&
           VerifyField<int16_t>(verifier, VT_FPS, 2) &&
           VerifyField<ss::runtime::Rect>(verifier, VT_CANVAS, 4) &&
           verifier.EndTable();
  }
};

struct AnimPrepDataBuilder {
  typedef AnimPrepData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parts_initial_attributes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributes>>> parts_initial_attributes) {
    fbb_.AddOffset(AnimPrepData::VT_PARTS_INITIAL_ATTRIBUTES, parts_initial_attributes);
  }
  void add_parts_mesh_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartMeshData>>> parts_mesh_data) {
    fbb_.AddOffset(AnimPrepData::VT_PARTS_MESH_DATA, parts_mesh_data);
  }
  void add_events(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventsPerFrame>>> events) {
    fbb_.AddOffset(AnimPrepData::VT_EVENTS, events);
  }
  void add_labels(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::Label>>> labels) {
    fbb_.AddOffset(AnimPrepData::VT_LABELS, labels);
  }
  void add_start_frame(int16_t start_frame) {
    fbb_.AddElement<int16_t>(AnimPrepData::VT_START_FRAME, start_frame, 0);
  }
  void add_end_frame(int16_t end_frame) {
    fbb_.AddElement<int16_t>(AnimPrepData::VT_END_FRAME, end_frame, 0);
  }
  void add_total_frame(int16_t total_frame) {
    fbb_.AddElement<int16_t>(AnimPrepData::VT_TOTAL_FRAME, total_frame, 0);
  }
  void add_fps(int16_t fps) {
    fbb_.AddElement<int16_t>(AnimPrepData::VT_FPS, fps, 0);
  }
  void add_canvas(const ss::runtime::Rect *canvas) {
    fbb_.AddStruct(AnimPrepData::VT_CANVAS, canvas);
  }
  explicit AnimPrepDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimPrepData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimPrepData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimPrepData> CreateAnimPrepData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributes>>> parts_initial_attributes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartMeshData>>> parts_mesh_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EventsPerFrame>>> events = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::Label>>> labels = 0,
    int16_t start_frame = 0,
    int16_t end_frame = 0,
    int16_t total_frame = 0,
    int16_t fps = 0,
    const ss::runtime::Rect *canvas = nullptr) {
  AnimPrepDataBuilder builder_(_fbb);
  builder_.add_canvas(canvas);
  builder_.add_labels(labels);
  builder_.add_events(events);
  builder_.add_parts_mesh_data(parts_mesh_data);
  builder_.add_parts_initial_attributes(parts_initial_attributes);
  builder_.add_fps(fps);
  builder_.add_total_frame(total_frame);
  builder_.add_end_frame(end_frame);
  builder_.add_start_frame(start_frame);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimPrepData> CreateAnimPrepDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ss::runtime::PartAttributes>> *parts_initial_attributes = nullptr,
    const std::vector<::flatbuffers::Offset<ss::runtime::PartMeshData>> *parts_mesh_data = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::EventsPerFrame>> *events = nullptr,
    std::vector<::flatbuffers::Offset<ss::runtime::Label>> *labels = nullptr,
    int16_t start_frame = 0,
    int16_t end_frame = 0,
    int16_t total_frame = 0,
    int16_t fps = 0,
    const ss::runtime::Rect *canvas = nullptr) {
  auto parts_initial_attributes__ = parts_initial_attributes ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::PartAttributes>>(*parts_initial_attributes) : 0;
  auto parts_mesh_data__ = parts_mesh_data ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::PartMeshData>>(*parts_mesh_data) : 0;
  auto events__ = events ? _fbb.CreateVectorOfSortedTables<ss::runtime::EventsPerFrame>(events) : 0;
  auto labels__ = labels ? _fbb.CreateVectorOfSortedTables<ss::runtime::Label>(labels) : 0;
  return ss::runtime::CreateAnimPrepData(
      _fbb,
      parts_initial_attributes__,
      parts_mesh_data__,
      events__,
      labels__,
      start_frame,
      end_frame,
      total_frame,
      fps,
      canvas);
}

inline const ss::runtime::AnimPrepData *GetAnimPrepData(const void *buf) {
  return ::flatbuffers::GetRoot<ss::runtime::AnimPrepData>(buf);
}

inline const ss::runtime::AnimPrepData *GetSizePrefixedAnimPrepData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ss::runtime::AnimPrepData>(buf);
}

template <bool B = false>
inline bool VerifyAnimPrepDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ss::runtime::AnimPrepData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedAnimPrepDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ss::runtime::AnimPrepData>(nullptr);
}

inline void FinishAnimPrepDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::AnimPrepData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimPrepDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::AnimPrepData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace runtime
}  // namespace ss

#endif  // FLATBUFFERS_GENERATED_PREPARATION_SS_RUNTIME_H_
