// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SSQB_H_
#define FLATBUFFERS_GENERATED_SSQB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct SequenceItem;
struct SequenceItemBuilder;

struct Sequence;
struct SequenceBuilder;

struct SsSequenceBinary;
struct SsSequenceBinaryBuilder;

enum SequenceType : uint8_t {
  SequenceType_Last = 0,
  SequenceType_Keep = 1,
  SequenceType_Top = 2,
  SequenceType_MIN = SequenceType_Last,
  SequenceType_MAX = SequenceType_Top
};

inline const SequenceType (&EnumValuesSequenceType())[3] {
  static const SequenceType values[] = {
    SequenceType_Last,
    SequenceType_Keep,
    SequenceType_Top
  };
  return values;
}

inline const char * const *EnumNamesSequenceType() {
  static const char * const names[4] = {
    "Last",
    "Keep",
    "Top",
    nullptr
  };
  return names;
}

inline const char *EnumNameSequenceType(SequenceType e) {
  if (::flatbuffers::IsOutRange(e, SequenceType_Last, SequenceType_Top)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSequenceType()[index];
}

struct SequenceItem FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SequenceItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REF_ANIME_PACK = 4,
    VT_REF_ANIME = 6,
    VT_REPEAT_COUNT = 8
  };
  const ::flatbuffers::String *ref_anime_pack() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REF_ANIME_PACK);
  }
  const ::flatbuffers::String *ref_anime() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REF_ANIME);
  }
  int32_t repeat_count() const {
    return GetField<int32_t>(VT_REPEAT_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REF_ANIME_PACK) &&
           verifier.VerifyString(ref_anime_pack()) &&
           VerifyOffset(verifier, VT_REF_ANIME) &&
           verifier.VerifyString(ref_anime()) &&
           VerifyField<int32_t>(verifier, VT_REPEAT_COUNT, 4) &&
           verifier.EndTable();
  }
};

struct SequenceItemBuilder {
  typedef SequenceItem Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ref_anime_pack(::flatbuffers::Offset<::flatbuffers::String> ref_anime_pack) {
    fbb_.AddOffset(SequenceItem::VT_REF_ANIME_PACK, ref_anime_pack);
  }
  void add_ref_anime(::flatbuffers::Offset<::flatbuffers::String> ref_anime) {
    fbb_.AddOffset(SequenceItem::VT_REF_ANIME, ref_anime);
  }
  void add_repeat_count(int32_t repeat_count) {
    fbb_.AddElement<int32_t>(SequenceItem::VT_REPEAT_COUNT, repeat_count, 0);
  }
  explicit SequenceItemBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SequenceItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SequenceItem>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SequenceItem> CreateSequenceItem(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ref_anime_pack = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ref_anime = 0,
    int32_t repeat_count = 0) {
  SequenceItemBuilder builder_(_fbb);
  builder_.add_repeat_count(repeat_count);
  builder_.add_ref_anime(ref_anime);
  builder_.add_ref_anime_pack(ref_anime_pack);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SequenceItem> CreateSequenceItemDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ref_anime_pack = nullptr,
    const char *ref_anime = nullptr,
    int32_t repeat_count = 0) {
  auto ref_anime_pack__ = ref_anime_pack ? _fbb.CreateString(ref_anime_pack) : 0;
  auto ref_anime__ = ref_anime ? _fbb.CreateString(ref_anime) : 0;
  return CreateSequenceItem(
      _fbb,
      ref_anime_pack__,
      ref_anime__,
      repeat_count);
}

struct Sequence FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SequenceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_INDEX = 6,
    VT_TYPE = 8,
    VT_LIST = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool KeyCompareLessThan(const Sequence * const o) const {
    return *name() < *o->name();
  }
  int KeyCompareWithValue(const char *_name) const {
    return strcmp(name()->c_str(), _name);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _name) const {
    if (name()->c_str() < _name) return -1;
    if (_name < name()->c_str()) return 1;
    return 0;
  }
  int32_t index() const {
    return GetField<int32_t>(VT_INDEX, 0);
  }
  SequenceType type() const {
    return static_cast<SequenceType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SequenceItem>> *list() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SequenceItem>> *>(VT_LIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_INDEX, 4) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_LIST) &&
           verifier.VerifyVector(list()) &&
           verifier.VerifyVectorOfTables(list()) &&
           verifier.EndTable();
  }
};

struct SequenceBuilder {
  typedef Sequence Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Sequence::VT_NAME, name);
  }
  void add_index(int32_t index) {
    fbb_.AddElement<int32_t>(Sequence::VT_INDEX, index, 0);
  }
  void add_type(SequenceType type) {
    fbb_.AddElement<uint8_t>(Sequence::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_list(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SequenceItem>>> list) {
    fbb_.AddOffset(Sequence::VT_LIST, list);
  }
  explicit SequenceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sequence> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sequence>(end);
    fbb_.Required(o, Sequence::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<Sequence> CreateSequence(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t index = 0,
    SequenceType type = SequenceType_Last,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SequenceItem>>> list = 0) {
  SequenceBuilder builder_(_fbb);
  builder_.add_list(list);
  builder_.add_index(index);
  builder_.add_name(name);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Sequence> CreateSequenceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t index = 0,
    SequenceType type = SequenceType_Last,
    const std::vector<::flatbuffers::Offset<SequenceItem>> *list = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto list__ = list ? _fbb.CreateVector<::flatbuffers::Offset<SequenceItem>>(*list) : 0;
  return CreateSequence(
      _fbb,
      name__,
      index,
      type,
      list__);
}

struct SsSequenceBinary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SsSequenceBinaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_SEQUENCE_LIST = 6
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Sequence>> *sequence_list() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Sequence>> *>(VT_SEQUENCE_LIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_SEQUENCE_LIST) &&
           verifier.VerifyVector(sequence_list()) &&
           verifier.VerifyVectorOfTables(sequence_list()) &&
           verifier.EndTable();
  }
};

struct SsSequenceBinaryBuilder {
  typedef SsSequenceBinary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(SsSequenceBinary::VT_VERSION, version, 1);
  }
  void add_sequence_list(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Sequence>>> sequence_list) {
    fbb_.AddOffset(SsSequenceBinary::VT_SEQUENCE_LIST, sequence_list);
  }
  explicit SsSequenceBinaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SsSequenceBinary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SsSequenceBinary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SsSequenceBinary> CreateSsSequenceBinary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Sequence>>> sequence_list = 0) {
  SsSequenceBinaryBuilder builder_(_fbb);
  builder_.add_sequence_list(sequence_list);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SsSequenceBinary> CreateSsSequenceBinaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    std::vector<::flatbuffers::Offset<Sequence>> *sequence_list = nullptr) {
  auto sequence_list__ = sequence_list ? _fbb.CreateVectorOfSortedTables<Sequence>(sequence_list) : 0;
  return CreateSsSequenceBinary(
      _fbb,
      version,
      sequence_list__);
}

inline const SsSequenceBinary *GetSsSequenceBinary(const void *buf) {
  return ::flatbuffers::GetRoot<SsSequenceBinary>(buf);
}

inline const SsSequenceBinary *GetSizePrefixedSsSequenceBinary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SsSequenceBinary>(buf);
}

inline const char *SsSequenceBinaryIdentifier() {
  return "SSQB";
}

inline bool SsSequenceBinaryBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SsSequenceBinaryIdentifier());
}

inline bool SizePrefixedSsSequenceBinaryBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SsSequenceBinaryIdentifier(), true);
}

template <bool B = false>
inline bool VerifySsSequenceBinaryBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<SsSequenceBinary>(SsSequenceBinaryIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedSsSequenceBinaryBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<SsSequenceBinary>(SsSequenceBinaryIdentifier());
}

inline const char *SsSequenceBinaryExtension() {
  return "ssqb";
}

inline void FinishSsSequenceBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SsSequenceBinary> root) {
  fbb.Finish(root, SsSequenceBinaryIdentifier());
}

inline void FinishSizePrefixedSsSequenceBinaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SsSequenceBinary> root) {
  fbb.FinishSizePrefixed(root, SsSequenceBinaryIdentifier());
}

#endif  // FLATBUFFERS_GENERATED_SSQB_H_
