#!/usr/bin/env python

Import("env")
Import("env_modules")
import os

env_gd_spritestudio = env_modules.Clone()

env_gd_spritestudio.add_source_files(env.modules_sources, "*.cpp")
env_gd_spritestudio.add_source_files(env.modules_sources, "flatbuffers/src/idl_parser.cpp")
env_gd_spritestudio.add_source_files(env.modules_sources, "flatbuffers/src/idl_gen_text.cpp")
env_gd_spritestudio.add_source_files(env.modules_sources, "flatbuffers/src/reflection.cpp")
env_gd_spritestudio.add_source_files(env.modules_sources, "flatbuffers/src/util.cpp")


env_gd_spritestudio.Append(
	CPPPATH=[
        "flatbuffers/src",
        "flatbuffers/include",
        "runtime",
	])

module_path = env.Dir('.').abspath
if env['platform'] == 'macos' or env['platform'] == 'windows':
    runtime_libpath = os.path.join(module_path, "runtime", "libs", env['platform'])
else:
    runtime_libpath = os.path.join(module_path, "runtime", "libs", env['platform'], env['arch'])

env.Append(
    LIBPATH=[
        runtime_libpath,
    ])

if env['target'] == 'editor':
    env.Append(LIBS=["ssconverter"])
env.Append(LIBS=["ssruntime"])


if not env_gd_spritestudio.msvc:
    env_gd_spritestudio.Append(CXXFLAGS=["-Wno-inconsistent-missing-override"])

if env['platform'] == 'macos':
    env_gd_spritestudio.Append(LINKFLAGS=['-framework', 'Metal'])
