name: Setup godot
description: Setup build dependencies for godot.

inputs:
  platform:
    required: true
    description: Target platform.

runs:
  using: composite
  steps:
    - name: prepare scons
      uses: ./.github/actions/setup-scons

    - name: install Vulkan SDK
      shell: bash
      run: |
          curl -L "https://sdk.lunarg.com/sdk/download/1.4.321.0/mac/vulkansdk-macos-1.4.321.0.zip" -o /tmp/vulkan-sdk.zip
          unzip /tmp/vulkan-sdk.zip -d /tmp/vulkan-sdk
          /tmp/vulkan-sdk/vulkansdk-macOS-1.4.321.0.app/Contents/MacOS/vulkansdk-macOS-1.4.321.0 --accept-licenses --default-answer --confirm-command install
          rm -f /tmp/vulkan-sdk.zip
          rm -rf /tmp/vulkan-sdk
      if: inputs.platform == 'macos'

    - name: Download Direct3D 12 SDK components
      shell: cmd
      run: python ./godot/misc/scripts/install_d3d12_sdk_windows.py
      if: inputs.platform == 'windows'

    - name: Download pre-built ANGLE static libraries
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: godotengine/godot-angle-static
        version: tags/chromium/6601.2
        file: godot-angle-static-x86_64-msvc-release.zip
        target: angle/angle.zip
      if: inputs.platform == 'windows'

    - name: Extract pre-built ANGLE static libraries
      shell: pwsh
      run: Expand-Archive -Force angle/angle.zip ${{github.workspace}}/
      if: inputs.platform == 'windows'
