// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EFFECTSTATE_SS_RUNTIME_H_
#define FLATBUFFERS_GENERATED_EFFECTSTATE_SS_RUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ss {
namespace runtime {

struct ParticleState;

struct EmitterState;
struct EmitterStateBuilder;

struct EffectState;
struct EffectStateBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ParticleState FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float scale_x_;
  float scale_y_;
  float rotation_;
  float direction_;
  uint8_t a_;
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  ParticleState()
      : x_(0),
        y_(0),
        scale_x_(0),
        scale_y_(0),
        rotation_(0),
        direction_(0),
        a_(0),
        r_(0),
        g_(0),
        b_(0) {
  }
  ParticleState(float _x, float _y, float _scale_x, float _scale_y, float _rotation, float _direction, uint8_t _a, uint8_t _r, uint8_t _g, uint8_t _b)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        scale_x_(::flatbuffers::EndianScalar(_scale_x)),
        scale_y_(::flatbuffers::EndianScalar(_scale_y)),
        rotation_(::flatbuffers::EndianScalar(_rotation)),
        direction_(::flatbuffers::EndianScalar(_direction)),
        a_(::flatbuffers::EndianScalar(_a)),
        r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float scale_x() const {
    return ::flatbuffers::EndianScalar(scale_x_);
  }
  float scale_y() const {
    return ::flatbuffers::EndianScalar(scale_y_);
  }
  float rotation() const {
    return ::flatbuffers::EndianScalar(rotation_);
  }
  float direction() const {
    return ::flatbuffers::EndianScalar(direction_);
  }
  uint8_t a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
  uint8_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(ParticleState, 28);

struct EmitterState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmitterStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CELL_NAME_HASH = 4,
    VT_CELL_MAP_NAME_HASH = 6,
    VT_BLEND_TYPE = 8,
    VT_PARTICLES = 10
  };
  uint32_t cell_name_hash() const {
    return GetField<uint32_t>(VT_CELL_NAME_HASH, 0);
  }
  uint32_t cell_map_name_hash() const {
    return GetField<uint32_t>(VT_CELL_MAP_NAME_HASH, 0);
  }
  int32_t blend_type() const {
    return GetField<int32_t>(VT_BLEND_TYPE, 0);
  }
  const ::flatbuffers::Vector<const ss::runtime::ParticleState *> *particles() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::ParticleState *> *>(VT_PARTICLES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CELL_NAME_HASH, 4) &&
           VerifyField<uint32_t>(verifier, VT_CELL_MAP_NAME_HASH, 4) &&
           VerifyField<int32_t>(verifier, VT_BLEND_TYPE, 4) &&
           VerifyOffset(verifier, VT_PARTICLES) &&
           verifier.VerifyVector(particles()) &&
           verifier.EndTable();
  }
};

struct EmitterStateBuilder {
  typedef EmitterState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cell_name_hash(uint32_t cell_name_hash) {
    fbb_.AddElement<uint32_t>(EmitterState::VT_CELL_NAME_HASH, cell_name_hash, 0);
  }
  void add_cell_map_name_hash(uint32_t cell_map_name_hash) {
    fbb_.AddElement<uint32_t>(EmitterState::VT_CELL_MAP_NAME_HASH, cell_map_name_hash, 0);
  }
  void add_blend_type(int32_t blend_type) {
    fbb_.AddElement<int32_t>(EmitterState::VT_BLEND_TYPE, blend_type, 0);
  }
  void add_particles(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::ParticleState *>> particles) {
    fbb_.AddOffset(EmitterState::VT_PARTICLES, particles);
  }
  explicit EmitterStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmitterState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmitterState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmitterState> CreateEmitterState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t cell_name_hash = 0,
    uint32_t cell_map_name_hash = 0,
    int32_t blend_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::ParticleState *>> particles = 0) {
  EmitterStateBuilder builder_(_fbb);
  builder_.add_particles(particles);
  builder_.add_blend_type(blend_type);
  builder_.add_cell_map_name_hash(cell_map_name_hash);
  builder_.add_cell_name_hash(cell_name_hash);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmitterState> CreateEmitterStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t cell_name_hash = 0,
    uint32_t cell_map_name_hash = 0,
    int32_t blend_type = 0,
    const std::vector<ss::runtime::ParticleState> *particles = nullptr) {
  auto particles__ = particles ? _fbb.CreateVectorOfStructs<ss::runtime::ParticleState>(*particles) : 0;
  return ss::runtime::CreateEmitterState(
      _fbb,
      cell_name_hash,
      cell_map_name_hash,
      blend_type,
      particles__);
}

struct EffectState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EffectStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EMITTERS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EmitterState>> *emitters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EmitterState>> *>(VT_EMITTERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_EMITTERS) &&
           verifier.VerifyVector(emitters()) &&
           verifier.VerifyVectorOfTables(emitters()) &&
           verifier.EndTable();
  }
};

struct EffectStateBuilder {
  typedef EffectState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_emitters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EmitterState>>> emitters) {
    fbb_.AddOffset(EffectState::VT_EMITTERS, emitters);
  }
  explicit EffectStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EffectState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EffectState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EffectState> CreateEffectState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::EmitterState>>> emitters = 0) {
  EffectStateBuilder builder_(_fbb);
  builder_.add_emitters(emitters);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EffectState> CreateEffectStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ss::runtime::EmitterState>> *emitters = nullptr) {
  auto emitters__ = emitters ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::EmitterState>>(*emitters) : 0;
  return ss::runtime::CreateEffectState(
      _fbb,
      emitters__);
}

inline const ss::runtime::EffectState *GetEffectState(const void *buf) {
  return ::flatbuffers::GetRoot<ss::runtime::EffectState>(buf);
}

inline const ss::runtime::EffectState *GetSizePrefixedEffectState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ss::runtime::EffectState>(buf);
}

template <bool B = false>
inline bool VerifyEffectStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ss::runtime::EffectState>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEffectStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ss::runtime::EffectState>(nullptr);
}

inline void FinishEffectStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::EffectState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEffectStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::EffectState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace runtime
}  // namespace ss

#endif  // FLATBUFFERS_GENERATED_EFFECTSTATE_SS_RUNTIME_H_
