// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EFFECTDRAWPLAN_SS_RUNTIME_H_
#define FLATBUFFERS_GENERATED_EFFECTDRAWPLAN_SS_RUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ss {
namespace runtime {

struct EffectDrawCommand;

struct EffectDrawPlan;
struct EffectDrawPlanBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) EffectDrawCommand FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t cellmap_hash_;
  uint32_t quad_count_;
  uint32_t particle_offset_;
  uint8_t blend_;
  int8_t padding0__;  int16_t padding1__;

 public:
  EffectDrawCommand()
      : cellmap_hash_(0),
        quad_count_(0),
        particle_offset_(0),
        blend_(0),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  EffectDrawCommand(uint32_t _cellmap_hash, uint32_t _quad_count, uint32_t _particle_offset, uint8_t _blend)
      : cellmap_hash_(::flatbuffers::EndianScalar(_cellmap_hash)),
        quad_count_(::flatbuffers::EndianScalar(_quad_count)),
        particle_offset_(::flatbuffers::EndianScalar(_particle_offset)),
        blend_(::flatbuffers::EndianScalar(_blend)),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  uint32_t cellmap_hash() const {
    return ::flatbuffers::EndianScalar(cellmap_hash_);
  }
  uint32_t quad_count() const {
    return ::flatbuffers::EndianScalar(quad_count_);
  }
  uint32_t particle_offset() const {
    return ::flatbuffers::EndianScalar(particle_offset_);
  }
  uint8_t blend() const {
    return ::flatbuffers::EndianScalar(blend_);
  }
};
FLATBUFFERS_STRUCT_END(EffectDrawCommand, 16);

struct EffectDrawPlan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EffectDrawPlanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMMANDS = 4,
    VT_VERT_STRIDE = 6,
    VT_VERTS = 8,
    VT_UVS = 10,
    VT_COLORS = 12,
    VT_INDICES = 14
  };
  const ::flatbuffers::Vector<const ss::runtime::EffectDrawCommand *> *commands() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::EffectDrawCommand *> *>(VT_COMMANDS);
  }
  uint8_t vert_stride() const {
    return GetField<uint8_t>(VT_VERT_STRIDE, 0);
  }
  const ::flatbuffers::Vector<float> *verts() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VERTS);
  }
  const ::flatbuffers::Vector<float> *uvs() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_UVS);
  }
  const ::flatbuffers::Vector<float> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<int32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_INDICES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyVector(commands()) &&
           VerifyField<uint8_t>(verifier, VT_VERT_STRIDE, 1) &&
           VerifyOffset(verifier, VT_VERTS) &&
           verifier.VerifyVector(verts()) &&
           VerifyOffset(verifier, VT_UVS) &&
           verifier.VerifyVector(uvs()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           verifier.EndTable();
  }
};

struct EffectDrawPlanBuilder {
  typedef EffectDrawPlan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_commands(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::EffectDrawCommand *>> commands) {
    fbb_.AddOffset(EffectDrawPlan::VT_COMMANDS, commands);
  }
  void add_vert_stride(uint8_t vert_stride) {
    fbb_.AddElement<uint8_t>(EffectDrawPlan::VT_VERT_STRIDE, vert_stride, 0);
  }
  void add_verts(::flatbuffers::Offset<::flatbuffers::Vector<float>> verts) {
    fbb_.AddOffset(EffectDrawPlan::VT_VERTS, verts);
  }
  void add_uvs(::flatbuffers::Offset<::flatbuffers::Vector<float>> uvs) {
    fbb_.AddOffset(EffectDrawPlan::VT_UVS, uvs);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<float>> colors) {
    fbb_.AddOffset(EffectDrawPlan::VT_COLORS, colors);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> indices) {
    fbb_.AddOffset(EffectDrawPlan::VT_INDICES, indices);
  }
  explicit EffectDrawPlanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EffectDrawPlan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EffectDrawPlan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EffectDrawPlan> CreateEffectDrawPlan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::EffectDrawCommand *>> commands = 0,
    uint8_t vert_stride = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> verts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> uvs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> indices = 0) {
  EffectDrawPlanBuilder builder_(_fbb);
  builder_.add_indices(indices);
  builder_.add_colors(colors);
  builder_.add_uvs(uvs);
  builder_.add_verts(verts);
  builder_.add_commands(commands);
  builder_.add_vert_stride(vert_stride);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EffectDrawPlan> CreateEffectDrawPlanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ss::runtime::EffectDrawCommand> *commands = nullptr,
    uint8_t vert_stride = 0,
    const std::vector<float> *verts = nullptr,
    const std::vector<float> *uvs = nullptr,
    const std::vector<float> *colors = nullptr,
    const std::vector<int32_t> *indices = nullptr) {
  auto commands__ = commands ? _fbb.CreateVectorOfStructs<ss::runtime::EffectDrawCommand>(*commands) : 0;
  auto verts__ = verts ? _fbb.CreateVector<float>(*verts) : 0;
  auto uvs__ = uvs ? _fbb.CreateVector<float>(*uvs) : 0;
  auto colors__ = colors ? _fbb.CreateVector<float>(*colors) : 0;
  auto indices__ = indices ? _fbb.CreateVector<int32_t>(*indices) : 0;
  return ss::runtime::CreateEffectDrawPlan(
      _fbb,
      commands__,
      vert_stride,
      verts__,
      uvs__,
      colors__,
      indices__);
}

inline const ss::runtime::EffectDrawPlan *GetEffectDrawPlan(const void *buf) {
  return ::flatbuffers::GetRoot<ss::runtime::EffectDrawPlan>(buf);
}

inline const ss::runtime::EffectDrawPlan *GetSizePrefixedEffectDrawPlan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ss::runtime::EffectDrawPlan>(buf);
}

template <bool B = false>
inline bool VerifyEffectDrawPlanBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ss::runtime::EffectDrawPlan>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEffectDrawPlanBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ss::runtime::EffectDrawPlan>(nullptr);
}

inline void FinishEffectDrawPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::EffectDrawPlan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEffectDrawPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::EffectDrawPlan> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace runtime
}  // namespace ss

#endif  // FLATBUFFERS_GENERATED_EFFECTDRAWPLAN_SS_RUNTIME_H_
