// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_
#define FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ss {
namespace runtime {

struct PartAttributeCell;

struct Vec2;

struct U8Rect;

struct SsAttributePartColorKeyValueColor;

struct PartAttributePartColor;

struct PartAttributeVertex;

struct PartAttributeDeform;
struct PartAttributeDeformBuilder;

struct PartAttributeShader;

struct PartState;

struct DrawBatch;

struct FrameData;
struct FrameDataBuilder;

enum BlendType : uint8_t {
  BlendType_Mix = 0,
  BlendType_Mul = 1,
  BlendType_Add = 2,
  BlendType_Sub = 3,
  BlendType_Mulalpha = 4,
  BlendType_Screen = 5,
  BlendType_Exclusion = 6,
  BlendType_Invert = 7,
  BlendType_Mul2 = 8,
  BlendType_Div2 = 9,
  BlendType_Screen2 = 10,
  BlendType_Overlay2 = 11,
  BlendType_MIN = BlendType_Mix,
  BlendType_MAX = BlendType_Overlay2
};

inline const BlendType (&EnumValuesBlendType())[12] {
  static const BlendType values[] = {
    BlendType_Mix,
    BlendType_Mul,
    BlendType_Add,
    BlendType_Sub,
    BlendType_Mulalpha,
    BlendType_Screen,
    BlendType_Exclusion,
    BlendType_Invert,
    BlendType_Mul2,
    BlendType_Div2,
    BlendType_Screen2,
    BlendType_Overlay2
  };
  return values;
}

inline const char * const *EnumNamesBlendType() {
  static const char * const names[13] = {
    "Mix",
    "Mul",
    "Add",
    "Sub",
    "Mulalpha",
    "Screen",
    "Exclusion",
    "Invert",
    "Mul2",
    "Div2",
    "Screen2",
    "Overlay2",
    nullptr
  };
  return names;
}

inline const char *EnumNameBlendType(BlendType e) {
  if (::flatbuffers::IsOutRange(e, BlendType_Mix, BlendType_Overlay2)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBlendType()[index];
}

enum UpdateAttributeFlags : uint64_t {
  UpdateAttributeFlags_AttributeCell = 1ULL,
  UpdateAttributeFlags_AttributePosX = 2ULL,
  UpdateAttributeFlags_AttributePosY = 4ULL,
  UpdateAttributeFlags_AttributePosZ = 8ULL,
  UpdateAttributeFlags_AttributeRotX = 16ULL,
  UpdateAttributeFlags_AttributeRotY = 32ULL,
  UpdateAttributeFlags_AttributeRotZ = 64ULL,
  UpdateAttributeFlags_AttributeSclX = 128ULL,
  UpdateAttributeFlags_AttributeSclY = 256ULL,
  UpdateAttributeFlags_AttributeLosclX = 512ULL,
  UpdateAttributeFlags_AttributeLosclY = 1024ULL,
  UpdateAttributeFlags_AttributeAlpha = 2048ULL,
  UpdateAttributeFlags_AttributeLoAlpha = 4096ULL,
  UpdateAttributeFlags_AttributePrio = 8192ULL,
  UpdateAttributeFlags_AttributeFlipH = 16384ULL,
  UpdateAttributeFlags_AttributeFlipV = 32768ULL,
  UpdateAttributeFlags_AttributeHide = 65536ULL,
  UpdateAttributeFlags_AttributePartColor = 131072ULL,
  UpdateAttributeFlags_AttributeShader = 262144ULL,
  UpdateAttributeFlags_AttributeVertex = 524288ULL,
  UpdateAttributeFlags_AttributePivotX = 1048576ULL,
  UpdateAttributeFlags_AttributePivotY = 2097152ULL,
  UpdateAttributeFlags_AttributeAnchorX = 4194304ULL,
  UpdateAttributeFlags_AttributeAnchorY = 8388608ULL,
  UpdateAttributeFlags_AttributeSizeX = 16777216ULL,
  UpdateAttributeFlags_AttributeSizeY = 33554432ULL,
  UpdateAttributeFlags_AttributeImgFlipH = 67108864ULL,
  UpdateAttributeFlags_AttributeImgFlipV = 134217728ULL,
  UpdateAttributeFlags_AttributeUvtX = 268435456ULL,
  UpdateAttributeFlags_AttributeUvtY = 536870912ULL,
  UpdateAttributeFlags_AttributeUvrZ = 1073741824ULL,
  UpdateAttributeFlags_AttributeUvsX = 2147483648ULL,
  UpdateAttributeFlags_AttributeUvsY = 4294967296ULL,
  UpdateAttributeFlags_AttributeBoundr = 8589934592ULL,
  UpdateAttributeFlags_AttributeMask = 17179869184ULL,
  UpdateAttributeFlags_AttributeSkew = 34359738368ULL,
  UpdateAttributeFlags_AttributeDeform = 68719476736ULL,
  UpdateAttributeFlags_AttributeTexture = 137438953472ULL,
  UpdateAttributeFlags_NONE = 0,
  UpdateAttributeFlags_ANY = 274877906943ULL
};

inline const UpdateAttributeFlags (&EnumValuesUpdateAttributeFlags())[38] {
  static const UpdateAttributeFlags values[] = {
    UpdateAttributeFlags_AttributeCell,
    UpdateAttributeFlags_AttributePosX,
    UpdateAttributeFlags_AttributePosY,
    UpdateAttributeFlags_AttributePosZ,
    UpdateAttributeFlags_AttributeRotX,
    UpdateAttributeFlags_AttributeRotY,
    UpdateAttributeFlags_AttributeRotZ,
    UpdateAttributeFlags_AttributeSclX,
    UpdateAttributeFlags_AttributeSclY,
    UpdateAttributeFlags_AttributeLosclX,
    UpdateAttributeFlags_AttributeLosclY,
    UpdateAttributeFlags_AttributeAlpha,
    UpdateAttributeFlags_AttributeLoAlpha,
    UpdateAttributeFlags_AttributePrio,
    UpdateAttributeFlags_AttributeFlipH,
    UpdateAttributeFlags_AttributeFlipV,
    UpdateAttributeFlags_AttributeHide,
    UpdateAttributeFlags_AttributePartColor,
    UpdateAttributeFlags_AttributeShader,
    UpdateAttributeFlags_AttributeVertex,
    UpdateAttributeFlags_AttributePivotX,
    UpdateAttributeFlags_AttributePivotY,
    UpdateAttributeFlags_AttributeAnchorX,
    UpdateAttributeFlags_AttributeAnchorY,
    UpdateAttributeFlags_AttributeSizeX,
    UpdateAttributeFlags_AttributeSizeY,
    UpdateAttributeFlags_AttributeImgFlipH,
    UpdateAttributeFlags_AttributeImgFlipV,
    UpdateAttributeFlags_AttributeUvtX,
    UpdateAttributeFlags_AttributeUvtY,
    UpdateAttributeFlags_AttributeUvrZ,
    UpdateAttributeFlags_AttributeUvsX,
    UpdateAttributeFlags_AttributeUvsY,
    UpdateAttributeFlags_AttributeBoundr,
    UpdateAttributeFlags_AttributeMask,
    UpdateAttributeFlags_AttributeSkew,
    UpdateAttributeFlags_AttributeDeform,
    UpdateAttributeFlags_AttributeTexture
  };
  return values;
}

inline const char *EnumNameUpdateAttributeFlags(UpdateAttributeFlags e) {
  switch (e) {
    case UpdateAttributeFlags_AttributeCell: return "AttributeCell";
    case UpdateAttributeFlags_AttributePosX: return "AttributePosX";
    case UpdateAttributeFlags_AttributePosY: return "AttributePosY";
    case UpdateAttributeFlags_AttributePosZ: return "AttributePosZ";
    case UpdateAttributeFlags_AttributeRotX: return "AttributeRotX";
    case UpdateAttributeFlags_AttributeRotY: return "AttributeRotY";
    case UpdateAttributeFlags_AttributeRotZ: return "AttributeRotZ";
    case UpdateAttributeFlags_AttributeSclX: return "AttributeSclX";
    case UpdateAttributeFlags_AttributeSclY: return "AttributeSclY";
    case UpdateAttributeFlags_AttributeLosclX: return "AttributeLosclX";
    case UpdateAttributeFlags_AttributeLosclY: return "AttributeLosclY";
    case UpdateAttributeFlags_AttributeAlpha: return "AttributeAlpha";
    case UpdateAttributeFlags_AttributeLoAlpha: return "AttributeLoAlpha";
    case UpdateAttributeFlags_AttributePrio: return "AttributePrio";
    case UpdateAttributeFlags_AttributeFlipH: return "AttributeFlipH";
    case UpdateAttributeFlags_AttributeFlipV: return "AttributeFlipV";
    case UpdateAttributeFlags_AttributeHide: return "AttributeHide";
    case UpdateAttributeFlags_AttributePartColor: return "AttributePartColor";
    case UpdateAttributeFlags_AttributeShader: return "AttributeShader";
    case UpdateAttributeFlags_AttributeVertex: return "AttributeVertex";
    case UpdateAttributeFlags_AttributePivotX: return "AttributePivotX";
    case UpdateAttributeFlags_AttributePivotY: return "AttributePivotY";
    case UpdateAttributeFlags_AttributeAnchorX: return "AttributeAnchorX";
    case UpdateAttributeFlags_AttributeAnchorY: return "AttributeAnchorY";
    case UpdateAttributeFlags_AttributeSizeX: return "AttributeSizeX";
    case UpdateAttributeFlags_AttributeSizeY: return "AttributeSizeY";
    case UpdateAttributeFlags_AttributeImgFlipH: return "AttributeImgFlipH";
    case UpdateAttributeFlags_AttributeImgFlipV: return "AttributeImgFlipV";
    case UpdateAttributeFlags_AttributeUvtX: return "AttributeUvtX";
    case UpdateAttributeFlags_AttributeUvtY: return "AttributeUvtY";
    case UpdateAttributeFlags_AttributeUvrZ: return "AttributeUvrZ";
    case UpdateAttributeFlags_AttributeUvsX: return "AttributeUvsX";
    case UpdateAttributeFlags_AttributeUvsY: return "AttributeUvsY";
    case UpdateAttributeFlags_AttributeBoundr: return "AttributeBoundr";
    case UpdateAttributeFlags_AttributeMask: return "AttributeMask";
    case UpdateAttributeFlags_AttributeSkew: return "AttributeSkew";
    case UpdateAttributeFlags_AttributeDeform: return "AttributeDeform";
    case UpdateAttributeFlags_AttributeTexture: return "AttributeTexture";
    default: return "";
  }
}

enum DrawBatchKind : uint8_t {
  DrawBatchKind_Normal = 0,
  DrawBatchKind_Shape = 1,
  DrawBatchKind_Instance = 2,
  DrawBatchKind_Effect = 3,
  DrawBatchKind_Mesh = 4,
  DrawBatchKind_Text = 5,
  DrawBatchKind_Nines = 6,
  DrawBatchKind_Mask = 7,
  DrawBatchKind_MIN = DrawBatchKind_Normal,
  DrawBatchKind_MAX = DrawBatchKind_Mask
};

inline const DrawBatchKind (&EnumValuesDrawBatchKind())[8] {
  static const DrawBatchKind values[] = {
    DrawBatchKind_Normal,
    DrawBatchKind_Shape,
    DrawBatchKind_Instance,
    DrawBatchKind_Effect,
    DrawBatchKind_Mesh,
    DrawBatchKind_Text,
    DrawBatchKind_Nines,
    DrawBatchKind_Mask
  };
  return values;
}

inline const char * const *EnumNamesDrawBatchKind() {
  static const char * const names[9] = {
    "Normal",
    "Shape",
    "Instance",
    "Effect",
    "Mesh",
    "Text",
    "Nines",
    "Mask",
    nullptr
  };
  return names;
}

inline const char *EnumNameDrawBatchKind(DrawBatchKind e) {
  if (::flatbuffers::IsOutRange(e, DrawBatchKind_Normal, DrawBatchKind_Mask)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDrawBatchKind()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PartAttributeCell FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t cellmap_name_hash_;
  uint32_t name_hash_;

 public:
  PartAttributeCell()
      : cellmap_name_hash_(0),
        name_hash_(0) {
  }
  PartAttributeCell(uint32_t _cellmap_name_hash, uint32_t _name_hash)
      : cellmap_name_hash_(::flatbuffers::EndianScalar(_cellmap_name_hash)),
        name_hash_(::flatbuffers::EndianScalar(_name_hash)) {
  }
  uint32_t cellmap_name_hash() const {
    return ::flatbuffers::EndianScalar(cellmap_name_hash_);
  }
  uint32_t name_hash() const {
    return ::flatbuffers::EndianScalar(name_hash_);
  }
};
FLATBUFFERS_STRUCT_END(PartAttributeCell, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) U8Rect FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t a_;
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  U8Rect()
      : a_(0),
        r_(0),
        g_(0),
        b_(0) {
  }
  U8Rect(uint8_t _a, uint8_t _r, uint8_t _g, uint8_t _b)
      : a_(::flatbuffers::EndianScalar(_a)),
        r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)) {
  }
  uint8_t a() const {
    return ::flatbuffers::EndianScalar(a_);
  }
  uint8_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(U8Rect, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) SsAttributePartColorKeyValueColor FLATBUFFERS_FINAL_CLASS {
 private:
  ss::runtime::U8Rect rgba_;
  float rate_;

 public:
  SsAttributePartColorKeyValueColor()
      : rgba_(),
        rate_(0) {
  }
  SsAttributePartColorKeyValueColor(const ss::runtime::U8Rect &_rgba, float _rate)
      : rgba_(_rgba),
        rate_(::flatbuffers::EndianScalar(_rate)) {
  }
  const ss::runtime::U8Rect &rgba() const {
    return rgba_;
  }
  float rate() const {
    return ::flatbuffers::EndianScalar(rate_);
  }
};
FLATBUFFERS_STRUCT_END(SsAttributePartColorKeyValueColor, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PartAttributePartColor FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t blend_type_;
  int8_t padding0__;  int16_t padding1__;
  ss::runtime::SsAttributePartColorKeyValueColor lt_;
  ss::runtime::SsAttributePartColorKeyValueColor rt_;
  ss::runtime::SsAttributePartColorKeyValueColor lb_;
  ss::runtime::SsAttributePartColorKeyValueColor rb_;

 public:
  PartAttributePartColor()
      : blend_type_(0),
        padding0__(0),
        padding1__(0),
        lt_(),
        rt_(),
        lb_(),
        rb_() {
    (void)padding0__;
    (void)padding1__;
  }
  PartAttributePartColor(ss::runtime::BlendType _blend_type, const ss::runtime::SsAttributePartColorKeyValueColor &_lt, const ss::runtime::SsAttributePartColorKeyValueColor &_rt, const ss::runtime::SsAttributePartColorKeyValueColor &_lb, const ss::runtime::SsAttributePartColorKeyValueColor &_rb)
      : blend_type_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_blend_type))),
        padding0__(0),
        padding1__(0),
        lt_(_lt),
        rt_(_rt),
        lb_(_lb),
        rb_(_rb) {
    (void)padding0__;
    (void)padding1__;
  }
  ss::runtime::BlendType blend_type() const {
    return static_cast<ss::runtime::BlendType>(::flatbuffers::EndianScalar(blend_type_));
  }
  const ss::runtime::SsAttributePartColorKeyValueColor &lt() const {
    return lt_;
  }
  const ss::runtime::SsAttributePartColorKeyValueColor &rt() const {
    return rt_;
  }
  const ss::runtime::SsAttributePartColorKeyValueColor &lb() const {
    return lb_;
  }
  const ss::runtime::SsAttributePartColorKeyValueColor &rb() const {
    return rb_;
  }
};
FLATBUFFERS_STRUCT_END(PartAttributePartColor, 36);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PartAttributeVertex FLATBUFFERS_FINAL_CLASS {
 private:
  ss::runtime::Vec2 lt_;
  ss::runtime::Vec2 rt_;
  ss::runtime::Vec2 lb_;
  ss::runtime::Vec2 rb_;
  ss::runtime::Vec2 center_;

 public:
  PartAttributeVertex()
      : lt_(),
        rt_(),
        lb_(),
        rb_(),
        center_() {
  }
  PartAttributeVertex(const ss::runtime::Vec2 &_lt, const ss::runtime::Vec2 &_rt, const ss::runtime::Vec2 &_lb, const ss::runtime::Vec2 &_rb, const ss::runtime::Vec2 &_center)
      : lt_(_lt),
        rt_(_rt),
        lb_(_lb),
        rb_(_rb),
        center_(_center) {
  }
  const ss::runtime::Vec2 &lt() const {
    return lt_;
  }
  const ss::runtime::Vec2 &rt() const {
    return rt_;
  }
  const ss::runtime::Vec2 &lb() const {
    return lb_;
  }
  const ss::runtime::Vec2 &rb() const {
    return rb_;
  }
  const ss::runtime::Vec2 &center() const {
    return center_;
  }
};
FLATBUFFERS_STRUCT_END(PartAttributeVertex, 40);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PartAttributeShader FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_hash_;
  float param0_;
  float param1_;
  float param2_;
  float param3_;
  float param4_;
  float param5_;
  float param6_;
  float param7_;
  uint32_t map0_cellmap_name_hash_;
  uint32_t map0_name_hash_;
  uint32_t map1_cellmap_name_hash_;
  uint32_t map1_name_hash_;

 public:
  PartAttributeShader()
      : id_hash_(0),
        param0_(0),
        param1_(0),
        param2_(0),
        param3_(0),
        param4_(0),
        param5_(0),
        param6_(0),
        param7_(0),
        map0_cellmap_name_hash_(0),
        map0_name_hash_(0),
        map1_cellmap_name_hash_(0),
        map1_name_hash_(0) {
  }
  PartAttributeShader(uint32_t _id_hash, float _param0, float _param1, float _param2, float _param3, float _param4, float _param5, float _param6, float _param7, uint32_t _map0_cellmap_name_hash, uint32_t _map0_name_hash, uint32_t _map1_cellmap_name_hash, uint32_t _map1_name_hash)
      : id_hash_(::flatbuffers::EndianScalar(_id_hash)),
        param0_(::flatbuffers::EndianScalar(_param0)),
        param1_(::flatbuffers::EndianScalar(_param1)),
        param2_(::flatbuffers::EndianScalar(_param2)),
        param3_(::flatbuffers::EndianScalar(_param3)),
        param4_(::flatbuffers::EndianScalar(_param4)),
        param5_(::flatbuffers::EndianScalar(_param5)),
        param6_(::flatbuffers::EndianScalar(_param6)),
        param7_(::flatbuffers::EndianScalar(_param7)),
        map0_cellmap_name_hash_(::flatbuffers::EndianScalar(_map0_cellmap_name_hash)),
        map0_name_hash_(::flatbuffers::EndianScalar(_map0_name_hash)),
        map1_cellmap_name_hash_(::flatbuffers::EndianScalar(_map1_cellmap_name_hash)),
        map1_name_hash_(::flatbuffers::EndianScalar(_map1_name_hash)) {
  }
  uint32_t id_hash() const {
    return ::flatbuffers::EndianScalar(id_hash_);
  }
  float param0() const {
    return ::flatbuffers::EndianScalar(param0_);
  }
  float param1() const {
    return ::flatbuffers::EndianScalar(param1_);
  }
  float param2() const {
    return ::flatbuffers::EndianScalar(param2_);
  }
  float param3() const {
    return ::flatbuffers::EndianScalar(param3_);
  }
  float param4() const {
    return ::flatbuffers::EndianScalar(param4_);
  }
  float param5() const {
    return ::flatbuffers::EndianScalar(param5_);
  }
  float param6() const {
    return ::flatbuffers::EndianScalar(param6_);
  }
  float param7() const {
    return ::flatbuffers::EndianScalar(param7_);
  }
  uint32_t map0_cellmap_name_hash() const {
    return ::flatbuffers::EndianScalar(map0_cellmap_name_hash_);
  }
  uint32_t map0_name_hash() const {
    return ::flatbuffers::EndianScalar(map0_name_hash_);
  }
  uint32_t map1_cellmap_name_hash() const {
    return ::flatbuffers::EndianScalar(map1_cellmap_name_hash_);
  }
  uint32_t map1_name_hash() const {
    return ::flatbuffers::EndianScalar(map1_name_hash_);
  }
};
FLATBUFFERS_STRUCT_END(PartAttributeShader, 52);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) PartState FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t update_flag_;
  float position_x_;
  float position_y_;
  float position_z_;
  float rotation_x_;
  float rotation_y_;
  float rotation_z_;
  float scale_x_;
  float scale_y_;
  float local_scale_x_;
  float local_scale_y_;
  float alpha_;
  float local_alpha_;
  float priority_;
  float pivot_x_;
  float pivot_y_;
  float anchor_x_;
  float anchor_y_;
  float size_x_;
  float size_y_;
  float uv_translation_x_;
  float uv_translation_y_;
  float uv_rotation_z_;
  float uv_scale_x_;
  float uv_scale_y_;
  float bounding_radius_;
  float mask_;
  float skew_x_;
  float skew_y_;
  uint32_t texture_;
  int16_t part_index_;
  int16_t cell_;
  int16_t part_color_;
  int16_t shader_;
  int16_t vertex_;
  int16_t deform_;
  uint8_t flip_h_;
  uint8_t flip_v_;
  uint8_t hide_;
  uint8_t img_flip_h_;
  uint8_t img_flip_v_;
  int8_t padding0__;  int16_t padding1__;

 public:
  PartState()
      : update_flag_(0),
        position_x_(0),
        position_y_(0),
        position_z_(0),
        rotation_x_(0),
        rotation_y_(0),
        rotation_z_(0),
        scale_x_(0),
        scale_y_(0),
        local_scale_x_(0),
        local_scale_y_(0),
        alpha_(0),
        local_alpha_(0),
        priority_(0),
        pivot_x_(0),
        pivot_y_(0),
        anchor_x_(0),
        anchor_y_(0),
        size_x_(0),
        size_y_(0),
        uv_translation_x_(0),
        uv_translation_y_(0),
        uv_rotation_z_(0),
        uv_scale_x_(0),
        uv_scale_y_(0),
        bounding_radius_(0),
        mask_(0),
        skew_x_(0),
        skew_y_(0),
        texture_(0),
        part_index_(0),
        cell_(0),
        part_color_(0),
        shader_(0),
        vertex_(0),
        deform_(0),
        flip_h_(0),
        flip_v_(0),
        hide_(0),
        img_flip_h_(0),
        img_flip_v_(0),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  PartState(ss::runtime::UpdateAttributeFlags _update_flag, float _position_x, float _position_y, float _position_z, float _rotation_x, float _rotation_y, float _rotation_z, float _scale_x, float _scale_y, float _local_scale_x, float _local_scale_y, float _alpha, float _local_alpha, float _priority, float _pivot_x, float _pivot_y, float _anchor_x, float _anchor_y, float _size_x, float _size_y, float _uv_translation_x, float _uv_translation_y, float _uv_rotation_z, float _uv_scale_x, float _uv_scale_y, float _bounding_radius, float _mask, float _skew_x, float _skew_y, uint32_t _texture, int16_t _part_index, int16_t _cell, int16_t _part_color, int16_t _shader, int16_t _vertex, int16_t _deform, bool _flip_h, bool _flip_v, bool _hide, bool _img_flip_h, bool _img_flip_v)
      : update_flag_(::flatbuffers::EndianScalar(static_cast<uint64_t>(_update_flag))),
        position_x_(::flatbuffers::EndianScalar(_position_x)),
        position_y_(::flatbuffers::EndianScalar(_position_y)),
        position_z_(::flatbuffers::EndianScalar(_position_z)),
        rotation_x_(::flatbuffers::EndianScalar(_rotation_x)),
        rotation_y_(::flatbuffers::EndianScalar(_rotation_y)),
        rotation_z_(::flatbuffers::EndianScalar(_rotation_z)),
        scale_x_(::flatbuffers::EndianScalar(_scale_x)),
        scale_y_(::flatbuffers::EndianScalar(_scale_y)),
        local_scale_x_(::flatbuffers::EndianScalar(_local_scale_x)),
        local_scale_y_(::flatbuffers::EndianScalar(_local_scale_y)),
        alpha_(::flatbuffers::EndianScalar(_alpha)),
        local_alpha_(::flatbuffers::EndianScalar(_local_alpha)),
        priority_(::flatbuffers::EndianScalar(_priority)),
        pivot_x_(::flatbuffers::EndianScalar(_pivot_x)),
        pivot_y_(::flatbuffers::EndianScalar(_pivot_y)),
        anchor_x_(::flatbuffers::EndianScalar(_anchor_x)),
        anchor_y_(::flatbuffers::EndianScalar(_anchor_y)),
        size_x_(::flatbuffers::EndianScalar(_size_x)),
        size_y_(::flatbuffers::EndianScalar(_size_y)),
        uv_translation_x_(::flatbuffers::EndianScalar(_uv_translation_x)),
        uv_translation_y_(::flatbuffers::EndianScalar(_uv_translation_y)),
        uv_rotation_z_(::flatbuffers::EndianScalar(_uv_rotation_z)),
        uv_scale_x_(::flatbuffers::EndianScalar(_uv_scale_x)),
        uv_scale_y_(::flatbuffers::EndianScalar(_uv_scale_y)),
        bounding_radius_(::flatbuffers::EndianScalar(_bounding_radius)),
        mask_(::flatbuffers::EndianScalar(_mask)),
        skew_x_(::flatbuffers::EndianScalar(_skew_x)),
        skew_y_(::flatbuffers::EndianScalar(_skew_y)),
        texture_(::flatbuffers::EndianScalar(_texture)),
        part_index_(::flatbuffers::EndianScalar(_part_index)),
        cell_(::flatbuffers::EndianScalar(_cell)),
        part_color_(::flatbuffers::EndianScalar(_part_color)),
        shader_(::flatbuffers::EndianScalar(_shader)),
        vertex_(::flatbuffers::EndianScalar(_vertex)),
        deform_(::flatbuffers::EndianScalar(_deform)),
        flip_h_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_flip_h))),
        flip_v_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_flip_v))),
        hide_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_hide))),
        img_flip_h_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_img_flip_h))),
        img_flip_v_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_img_flip_v))),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  ss::runtime::UpdateAttributeFlags update_flag() const {
    return static_cast<ss::runtime::UpdateAttributeFlags>(::flatbuffers::EndianScalar(update_flag_));
  }
  float position_x() const {
    return ::flatbuffers::EndianScalar(position_x_);
  }
  float position_y() const {
    return ::flatbuffers::EndianScalar(position_y_);
  }
  float position_z() const {
    return ::flatbuffers::EndianScalar(position_z_);
  }
  float rotation_x() const {
    return ::flatbuffers::EndianScalar(rotation_x_);
  }
  float rotation_y() const {
    return ::flatbuffers::EndianScalar(rotation_y_);
  }
  float rotation_z() const {
    return ::flatbuffers::EndianScalar(rotation_z_);
  }
  float scale_x() const {
    return ::flatbuffers::EndianScalar(scale_x_);
  }
  float scale_y() const {
    return ::flatbuffers::EndianScalar(scale_y_);
  }
  float local_scale_x() const {
    return ::flatbuffers::EndianScalar(local_scale_x_);
  }
  float local_scale_y() const {
    return ::flatbuffers::EndianScalar(local_scale_y_);
  }
  float alpha() const {
    return ::flatbuffers::EndianScalar(alpha_);
  }
  float local_alpha() const {
    return ::flatbuffers::EndianScalar(local_alpha_);
  }
  float priority() const {
    return ::flatbuffers::EndianScalar(priority_);
  }
  float pivot_x() const {
    return ::flatbuffers::EndianScalar(pivot_x_);
  }
  float pivot_y() const {
    return ::flatbuffers::EndianScalar(pivot_y_);
  }
  float anchor_x() const {
    return ::flatbuffers::EndianScalar(anchor_x_);
  }
  float anchor_y() const {
    return ::flatbuffers::EndianScalar(anchor_y_);
  }
  float size_x() const {
    return ::flatbuffers::EndianScalar(size_x_);
  }
  float size_y() const {
    return ::flatbuffers::EndianScalar(size_y_);
  }
  float uv_translation_x() const {
    return ::flatbuffers::EndianScalar(uv_translation_x_);
  }
  float uv_translation_y() const {
    return ::flatbuffers::EndianScalar(uv_translation_y_);
  }
  float uv_rotation_z() const {
    return ::flatbuffers::EndianScalar(uv_rotation_z_);
  }
  float uv_scale_x() const {
    return ::flatbuffers::EndianScalar(uv_scale_x_);
  }
  float uv_scale_y() const {
    return ::flatbuffers::EndianScalar(uv_scale_y_);
  }
  float bounding_radius() const {
    return ::flatbuffers::EndianScalar(bounding_radius_);
  }
  float mask() const {
    return ::flatbuffers::EndianScalar(mask_);
  }
  float skew_x() const {
    return ::flatbuffers::EndianScalar(skew_x_);
  }
  float skew_y() const {
    return ::flatbuffers::EndianScalar(skew_y_);
  }
  uint32_t texture() const {
    return ::flatbuffers::EndianScalar(texture_);
  }
  int16_t part_index() const {
    return ::flatbuffers::EndianScalar(part_index_);
  }
  int16_t cell() const {
    return ::flatbuffers::EndianScalar(cell_);
  }
  int16_t part_color() const {
    return ::flatbuffers::EndianScalar(part_color_);
  }
  int16_t shader() const {
    return ::flatbuffers::EndianScalar(shader_);
  }
  int16_t vertex() const {
    return ::flatbuffers::EndianScalar(vertex_);
  }
  int16_t deform() const {
    return ::flatbuffers::EndianScalar(deform_);
  }
  bool flip_h() const {
    return ::flatbuffers::EndianScalar(flip_h_) != 0;
  }
  bool flip_v() const {
    return ::flatbuffers::EndianScalar(flip_v_) != 0;
  }
  bool hide() const {
    return ::flatbuffers::EndianScalar(hide_) != 0;
  }
  bool img_flip_h() const {
    return ::flatbuffers::EndianScalar(img_flip_h_) != 0;
  }
  bool img_flip_v() const {
    return ::flatbuffers::EndianScalar(img_flip_v_) != 0;
  }
};
FLATBUFFERS_STRUCT_END(PartState, 144);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) DrawBatch FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t start_rank_;
  uint16_t count_;
  uint32_t texture_hash_;
  uint16_t vertex_count_;
  uint16_t index_count_;
  uint8_t blend_type_;
  uint8_t kind_;
  uint8_t flags_;
  uint8_t _reserved_;

 public:
  DrawBatch()
      : start_rank_(0),
        count_(0),
        texture_hash_(0),
        vertex_count_(0),
        index_count_(0),
        blend_type_(0),
        kind_(0),
        flags_(0),
        _reserved_(0) {
  }
  DrawBatch(uint16_t _start_rank, uint16_t _count, uint32_t _texture_hash, uint16_t _vertex_count, uint16_t _index_count, ss::runtime::BlendType _blend_type, ss::runtime::DrawBatchKind _kind, uint8_t _flags, uint8_t __reserved)
      : start_rank_(::flatbuffers::EndianScalar(_start_rank)),
        count_(::flatbuffers::EndianScalar(_count)),
        texture_hash_(::flatbuffers::EndianScalar(_texture_hash)),
        vertex_count_(::flatbuffers::EndianScalar(_vertex_count)),
        index_count_(::flatbuffers::EndianScalar(_index_count)),
        blend_type_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_blend_type))),
        kind_(::flatbuffers::EndianScalar(static_cast<uint8_t>(_kind))),
        flags_(::flatbuffers::EndianScalar(_flags)),
        _reserved_(::flatbuffers::EndianScalar(__reserved)) {
  }
  uint16_t start_rank() const {
    return ::flatbuffers::EndianScalar(start_rank_);
  }
  uint16_t count() const {
    return ::flatbuffers::EndianScalar(count_);
  }
  uint32_t texture_hash() const {
    return ::flatbuffers::EndianScalar(texture_hash_);
  }
  uint16_t vertex_count() const {
    return ::flatbuffers::EndianScalar(vertex_count_);
  }
  uint16_t index_count() const {
    return ::flatbuffers::EndianScalar(index_count_);
  }
  ss::runtime::BlendType blend_type() const {
    return static_cast<ss::runtime::BlendType>(::flatbuffers::EndianScalar(blend_type_));
  }
  ss::runtime::DrawBatchKind kind() const {
    return static_cast<ss::runtime::DrawBatchKind>(::flatbuffers::EndianScalar(kind_));
  }
  uint8_t flags() const {
    return ::flatbuffers::EndianScalar(flags_);
  }
  uint8_t _reserved() const {
    return ::flatbuffers::EndianScalar(_reserved_);
  }
};
FLATBUFFERS_STRUCT_END(DrawBatch, 16);

struct PartAttributeDeform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartAttributeDeformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COORDINATE = 4,
    VT_INDEX = 6
  };
  const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *coordinate() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::Vec2 *> *>(VT_COORDINATE);
  }
  const ::flatbuffers::Vector<int16_t> *index() const {
    return GetPointer<const ::flatbuffers::Vector<int16_t> *>(VT_INDEX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COORDINATE) &&
           verifier.VerifyVector(coordinate()) &&
           VerifyOffset(verifier, VT_INDEX) &&
           verifier.VerifyVector(index()) &&
           verifier.EndTable();
  }
};

struct PartAttributeDeformBuilder {
  typedef PartAttributeDeform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_coordinate(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate) {
    fbb_.AddOffset(PartAttributeDeform::VT_COORDINATE, coordinate);
  }
  void add_index(::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index) {
    fbb_.AddOffset(PartAttributeDeform::VT_INDEX, index);
  }
  explicit PartAttributeDeformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartAttributeDeform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartAttributeDeform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::Vec2 *>> coordinate = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> index = 0) {
  PartAttributeDeformBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_coordinate(coordinate);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartAttributeDeform> CreatePartAttributeDeformDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ss::runtime::Vec2> *coordinate = nullptr,
    const std::vector<int16_t> *index = nullptr) {
  auto coordinate__ = coordinate ? _fbb.CreateVectorOfStructs<ss::runtime::Vec2>(*coordinate) : 0;
  auto index__ = index ? _fbb.CreateVector<int16_t>(*index) : 0;
  return ss::runtime::CreatePartAttributeDeform(
      _fbb,
      coordinate__,
      index__);
}

struct FrameData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FrameDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTS = 4,
    VT_CELLS = 6,
    VT_PARTS_COLOR = 8,
    VT_SHADERS = 10,
    VT_VERTICES = 12,
    VT_DEFORMS = 14,
    VT_DRAW_ORDER = 16,
    VT_DRAW_BATCHES = 18
  };
  const ::flatbuffers::Vector<const ss::runtime::PartState *> *parts() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::PartState *> *>(VT_PARTS);
  }
  const ::flatbuffers::Vector<const ss::runtime::PartAttributeCell *> *cells() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::PartAttributeCell *> *>(VT_CELLS);
  }
  const ::flatbuffers::Vector<const ss::runtime::PartAttributePartColor *> *parts_color() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::PartAttributePartColor *> *>(VT_PARTS_COLOR);
  }
  const ::flatbuffers::Vector<const ss::runtime::PartAttributeShader *> *shaders() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::PartAttributeShader *> *>(VT_SHADERS);
  }
  const ::flatbuffers::Vector<const ss::runtime::PartAttributeVertex *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::PartAttributeVertex *> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>> *deforms() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>> *>(VT_DEFORMS);
  }
  const ::flatbuffers::Vector<uint16_t> *draw_order() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_DRAW_ORDER);
  }
  const ::flatbuffers::Vector<const ss::runtime::DrawBatch *> *draw_batches() const {
    return GetPointer<const ::flatbuffers::Vector<const ss::runtime::DrawBatch *> *>(VT_DRAW_BATCHES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARTS) &&
           verifier.VerifyVector(parts()) &&
           VerifyOffset(verifier, VT_CELLS) &&
           verifier.VerifyVector(cells()) &&
           VerifyOffset(verifier, VT_PARTS_COLOR) &&
           verifier.VerifyVector(parts_color()) &&
           VerifyOffset(verifier, VT_SHADERS) &&
           verifier.VerifyVector(shaders()) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           VerifyOffset(verifier, VT_DEFORMS) &&
           verifier.VerifyVector(deforms()) &&
           verifier.VerifyVectorOfTables(deforms()) &&
           VerifyOffset(verifier, VT_DRAW_ORDER) &&
           verifier.VerifyVector(draw_order()) &&
           VerifyOffset(verifier, VT_DRAW_BATCHES) &&
           verifier.VerifyVector(draw_batches()) &&
           verifier.EndTable();
  }
};

struct FrameDataBuilder {
  typedef FrameData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parts(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartState *>> parts) {
    fbb_.AddOffset(FrameData::VT_PARTS, parts);
  }
  void add_cells(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeCell *>> cells) {
    fbb_.AddOffset(FrameData::VT_CELLS, cells);
  }
  void add_parts_color(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributePartColor *>> parts_color) {
    fbb_.AddOffset(FrameData::VT_PARTS_COLOR, parts_color);
  }
  void add_shaders(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeShader *>> shaders) {
    fbb_.AddOffset(FrameData::VT_SHADERS, shaders);
  }
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeVertex *>> vertices) {
    fbb_.AddOffset(FrameData::VT_VERTICES, vertices);
  }
  void add_deforms(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>>> deforms) {
    fbb_.AddOffset(FrameData::VT_DEFORMS, deforms);
  }
  void add_draw_order(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> draw_order) {
    fbb_.AddOffset(FrameData::VT_DRAW_ORDER, draw_order);
  }
  void add_draw_batches(::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::DrawBatch *>> draw_batches) {
    fbb_.AddOffset(FrameData::VT_DRAW_BATCHES, draw_batches);
  }
  explicit FrameDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FrameData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FrameData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FrameData> CreateFrameData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartState *>> parts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeCell *>> cells = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributePartColor *>> parts_color = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeShader *>> shaders = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::PartAttributeVertex *>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>>> deforms = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> draw_order = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ss::runtime::DrawBatch *>> draw_batches = 0) {
  FrameDataBuilder builder_(_fbb);
  builder_.add_draw_batches(draw_batches);
  builder_.add_draw_order(draw_order);
  builder_.add_deforms(deforms);
  builder_.add_vertices(vertices);
  builder_.add_shaders(shaders);
  builder_.add_parts_color(parts_color);
  builder_.add_cells(cells);
  builder_.add_parts(parts);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FrameData> CreateFrameDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ss::runtime::PartState> *parts = nullptr,
    const std::vector<ss::runtime::PartAttributeCell> *cells = nullptr,
    const std::vector<ss::runtime::PartAttributePartColor> *parts_color = nullptr,
    const std::vector<ss::runtime::PartAttributeShader> *shaders = nullptr,
    const std::vector<ss::runtime::PartAttributeVertex> *vertices = nullptr,
    const std::vector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>> *deforms = nullptr,
    const std::vector<uint16_t> *draw_order = nullptr,
    const std::vector<ss::runtime::DrawBatch> *draw_batches = nullptr) {
  auto parts__ = parts ? _fbb.CreateVectorOfStructs<ss::runtime::PartState>(*parts) : 0;
  auto cells__ = cells ? _fbb.CreateVectorOfStructs<ss::runtime::PartAttributeCell>(*cells) : 0;
  auto parts_color__ = parts_color ? _fbb.CreateVectorOfStructs<ss::runtime::PartAttributePartColor>(*parts_color) : 0;
  auto shaders__ = shaders ? _fbb.CreateVectorOfStructs<ss::runtime::PartAttributeShader>(*shaders) : 0;
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<ss::runtime::PartAttributeVertex>(*vertices) : 0;
  auto deforms__ = deforms ? _fbb.CreateVector<::flatbuffers::Offset<ss::runtime::PartAttributeDeform>>(*deforms) : 0;
  auto draw_order__ = draw_order ? _fbb.CreateVector<uint16_t>(*draw_order) : 0;
  auto draw_batches__ = draw_batches ? _fbb.CreateVectorOfStructs<ss::runtime::DrawBatch>(*draw_batches) : 0;
  return ss::runtime::CreateFrameData(
      _fbb,
      parts__,
      cells__,
      parts_color__,
      shaders__,
      vertices__,
      deforms__,
      draw_order__,
      draw_batches__);
}

inline const ss::runtime::FrameData *GetFrameData(const void *buf) {
  return ::flatbuffers::GetRoot<ss::runtime::FrameData>(buf);
}

inline const ss::runtime::FrameData *GetSizePrefixedFrameData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ss::runtime::FrameData>(buf);
}

template <bool B = false>
inline bool VerifyFrameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ss::runtime::FrameData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedFrameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ss::runtime::FrameData>(nullptr);
}

inline void FinishFrameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::FrameData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFrameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ss::runtime::FrameData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace runtime
}  // namespace ss

#endif  // FLATBUFFERS_GENERATED_FRAMEDATA_SS_RUNTIME_H_
