name: CI

on:
  pull_request:
    branches:
      - main

env:
  GODOT_VERSION_4: 4.4
  PYTHONIOENCODING: utf8

jobs:
  godot:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Godot 4.x 🏁 Windows (x86_64, MSVC)
            os: windows-latest
            platform: windows

          - name: Godot 4.x 🍎 macOS (universal)
            os: macos-latest
            platform: macos

    defaults:
      run:
        shell: zsh {0}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: clone Godot repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: ${{ env.GODOT_VERSION_4 }}
        owner: 'godotengine'
        repository: 'godot'

    - name: setup for godot
      uses: ./.github/actions/setup-godot
      with:
        platform: ${{ matrix.platform }}

    - name: build godot
      if: matrix.platform == 'macos'
      run: |
        ./scripts/build.sh arch=universal compiledb=no strip=yes
    - name: build godot
      if: matrix.platform == 'windows'
      shell: pwsh
      run: |
        .\scripts\build.ps1 compiledb=no strip=yes
